<?php

/**
 * Test class for HomeNet_Model_ComponentModel_Service.
 * Generated by PHPUnit on 2011-11-21 at 16:36:23.
 */
class HomeNet_Model_ComponentModel_ServiceTest extends PHPUnit_Framework_TestCase {

    /**
     * @var HomeNet_Model_ComponentModel_Service
     */
    protected $service;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->service = new HomeNet_Model_ComponentModel_Service;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        $this->service->deleteAll();
    }
    
    private function _fillObject($object, $seed = 0) {
        $data = $this->_getTestData($seed);
        foreach ($data as $key => $value) {
            $object->$key = $value;
        }
        return $object;
    }
    private function _fillArray($array, $seed = 0) {
        if(is_object($array)){
            $array = $array->toArray();
        }
        return array_merge($array, $this->_getTestData($seed));
    }
    
    private function _getTestData($seed = 0) {
        
        $array = array('status' => HomeNet_Model_ComponentModel::LIVE,
        'plugin' => 'LED',
        'name' => 'testModel'.$seed,
        'description' => 'test description'.$seed,
        'datatype' => $seed,
        'settings' => array('key' => 'value'.$seed));
        
        if($seed % 2 == 0){
            $array['status'] = HomeNet_Model_ComponentModel::TESTING;
            $array['plugin'] = 'RGBLED';
        }
        return $array;
    }
    
    private function _createValidObject($seed = 0) {
        $object = new HomeNet_Model_ComponentModel();
        $object = $this->_fillObject($object, $seed);
  
        $result = $this->service->create($object);

        $this->assertInstanceOf('HomeNet_Model_ComponentModel_Interface', $result);
        return $result;
    }
     private function _validateResult($result, $seed = 0){
        
        $this->assertInstanceOf('HomeNet_Model_ComponentModel_Interface', $result);
        $this->assertNotNull($result->id);
        
        if($seed % 2 == 0){
            $this->assertEquals(HomeNet_Model_ComponentModel::TESTING, $result->status);
            $this->assertEquals('RGBLED', $result->plugin);
        } else {
            $this->assertEquals(HomeNet_Model_ComponentModel::LIVE, $result->status);
            $this->assertEquals('LED', $result->plugin);
        }
        $this->assertEquals('testModel'.$seed, $result->name);
        $this->assertEquals('test description'.$seed, $result->description);
        $this->assertEquals($seed, $result->datatype);
        $this->assertTrue(is_array($result->settings));
        $this->assertEquals('value'.$seed, $result->settings['key']);
    }
    
//$this->service->getMapper()///////////////////////////////////////////////////
    public function testGetMapper() {
       $this->assertInstanceOf('HomeNet_Model_ComponentModel_MapperInterface', $this->service->getMapper());
    }
    
//$this->service->setMapper($mapper)////////////////////////////////////////////
    public function testSetMapper() {
        $mapper = new HomeNet_Model_ComponentModel_MapperDbTable();
         $this->service->setMapper($mapper);
        
        $this->assertInstanceOf('HomeNet_Model_ComponentModel_MapperInterface', $this->service->getMapper());
        $this->assertEquals($mapper, $this->service->getMapper());
    }
    
//$this->service->getObjectById($id)////////////////////////////////////////////
   public function testGetObjectById_valid() {
        $object = $this->_createValidObject();

        $result = $this->service->getObjectById($object->id);

       
    }

    public function testGetObjectById_invalid() {
        $this->setExpectedException('NotFoundException');
        $result = $this->service->getObjectById(1000);
    }

    public function testGetObjectById_null() {
        $this->setExpectedException('InvalidArgumentException');
        $result = $this->service->getObjectById(null);
    }

//$this->service->getObjectsByIds($ids)/////////////////////////////////////////
    public function testGetObjectsByIds_valid() {
        $object = $this->_createValidObject(1);
        $object2 = $this->_createValidObject(2);
        $object3 = $this->_createValidObject(3);
        
        $results = $this->service->getObjectsByIds(array($object->id, $object2->id));
        
        $this->assertEquals(2, count($results));
        reset($results);
        $result = current($results);
        $this->_validateResult($result,1);
    }
    
    public function testGetObjectsByIds_empty() {

        $this->setExpectedException('InvalidArgumentException');
        $this->service->getObjectsByIds(array());
    }
    
    public function testGetObjectsByIds_invalidId() {

        $this->setExpectedException('InvalidArgumentException');
        $this->service->getObjectsByIds(array('string'));
    }
    
    public function testGetObjectsByIds_notFound() {

        $this->setExpectedException('NotFoundException');
        $this->service->getObjectsByIds(array(1000,1001));
    }
//$this->service->getObjects()//////////////////////////////////////////////////
    public function testGetObjects() {
        $object = $this->_createValidObject(1);
        $object2 = $this->_createValidObject(2);
        
        $results = $this->service->getObjects();
        
        $this->assertEquals(2, count($results));
        
        $result = $results[0];
        $this->_validateResult($result,1);
    }

//    public function testGetComponentsByIds_valid() {
//        $object = $this->_createValidObject();
//        
//        $results = $this->service->getComponentsByIds(array($object->id));
//        
//        $this->assertEquals(1, count($results));
//        
//        $result = $results[0];
//        $this->assertInstanceOf('HomeNet_Model_Component_Abstract', $result);
//        
//    }
//    
//    public function testGetComponentsByIds_empty() {
//        $this->setExpectedException('InvalidArgumentException');
//        $results = $this->service->getComponentsByIds(array());
//    }
//    
//     public function testGetObjectsByIds_notFound() {
//        $this->setExpectedException('NotFoundException');
//        $results = $this->service->getObjectsByIds(array(1000));
//    }
//$this->service->create($mixed)////////////////////////////////////////////////
    public function testCreate_validObject() {
        $result = $this->_createValidObject();
        $this->_validateResult($result);
    }

    public function testCreate_validArray() {
        $array = $this->_getTestData();

        $result = $this->service->create($array);

        $this->_validateResult($result);
    }
    
    public function testCreate_invalidObject() {
        $this->setExpectedException('InvalidArgumentException');

        $badObject = new StdClass();
        $this->service->create($badObject);
    }
    
//$this->service->update($mixed)////////////////////////////////////////////////
    public function testUpdate_validObject() {
        //setup
        $object = $this->_createValidObject();

        //update values
        $object = $this->_fillObject($object, 1);

        $result = $this->service->update($object);

        $this->_validateResult($result, 1);
    }

    public function testUpdate_validArray() {
        //setup
        $object = $this->_createValidObject();
        $array = $object->toArray();

        //update values
        $array = $this->_fillArray($array, 1);

        $result = $this->service->update($array);

        $this->assertInstanceOf('HomeNet_Model_ComponentModel_Interface', $result);

        $this->_validateResult($result, 1);
    }

    public function testUpdate_invalidObject() {
        $this->setExpectedException('InvalidArgumentException');

        $badObject = new StdClass();
        $create = $this->service->update($badObject);
    }
    
//$this->service->delete($mixed)////////////////////////////////////////////////
    public function testDelete_validObject() {
        //setup
        $object = $this->_createValidObject();

        //test delete
        $id = $object->id;
        $this->service->delete($object);

        //verify that it was deleted
        $this->setExpectedException('NotFoundException');
        $result = $this->service->getObjectById($id);
    }
    
    public function testDelete_validArray() {
        //setup
        $object = $this->_createValidObject();

        //test delete
        $id = $object->id;
        $this->service->delete($object->toArray());

        //verify that it was deleted
        $this->setExpectedException('NotFoundException');
        $result = $this->service->getObjectById($id);
    }

    public function testDelete_validId() {
        //setup
        $object = $this->_createValidObject();

        //test delete
        $id = $object->id;
        $this->service->delete($object->id);

        //verify that it was deleted
        $this->setExpectedException('NotFoundException');
        $result = $this->service->getObjectById($id);
    }

    public function testDelete_invalidObject() {
        $this->setExpectedException('InvalidArgumentException');

        $badObject = new StdClass();
        $create = $this->service->delete($badObject);
    }
}