<?php echo $this->heading($this->controllerTitle); ?>

<?php $types = array(0 =>'System', 1 => 'Template', 2 => 'User'); ?>

<p><a class="button"  href="<?php echo $this->url(array('controller' => 'section', 'action' => 'index'),'content-admin'); ?>">Back to Section</a></p>

<table class="ui-widget" width="100%">
    <thead class="ui-widget-header">
        <tr><th>Name</th><th>Last Revision</th><th>Type</th> <th width="150">Edit/Delete</th></tr>
    </thead>
    <tbody class="ui-widget-content">
        <?php
        foreach ($this->objects as $object) {
            /* @var $object Content_Model_Category */ //*
            ?>
            <tr  class="<?php echo $this->cycle(array("", "ui-state-highlight"))->next() ?>" >
                <td class="left"><?php echo $object->url ?></td>
                <td><?php echo $object->revision ?></td>
                <td><?php //echo  $types[$object->type] ?></td>
                <td><a href="<?php echo $this->url(array('controller' => 'template', 'id' => $object->id, 'action' => 'edit'),'content-admin-id'); ?>">Edit</a> <a href="<?php echo $this->url(array('controller' => 'template', 'id' => $object->id, 'action' => 'delete'),'content-admin-id'); ?>">Delete</a></td>
            </tr><?php //*/// print_r($object->toArray());
        }
        ?>
    </tbody>
</table>
<a class="button"  href="<?php echo $this->url(array('controller' => 'template', 'id' => $this->id, 'action' => 'new'),'content-admin-id'); ?>">New</a>
