<?php

//require_once dirname(__FILE__) . '/../../../../../../application/modules/Content/models/CategorySet/Service.php';

/**
 * Test class for Content_Model_CategorySet_Service.
 * Generated by PHPUnit on 2011-06-22 at 08:00:46.
 */
class Content_Model_CategorySet_ServiceTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Content_Model_Category_Service
     */
    protected $service;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->service = new Content_Model_CategorySet_Service();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        $this->service->deleteAll();
    }

    public function testGetMapper() {

        $this->assertInstanceOf('Content_Model_CategorySet_MapperInterface', $this->service->getMapper());
    }

    /**
     * @todo Implement testSetMapper().
     */
    public function testSetMapper() {
        
        $mapper = new Content_Model_CategorySet_MapperDbTable();
         $this->service->setMapper($mapper);
        
        $this->assertInstanceOf('Content_Model_CategorySet_MapperInterface', $this->service->getMapper());
        $this->assertEquals($mapper, $this->service->getMapper());
        //$this->ass
    }

    private function createValidObject() {
        $categorySet = new Content_Model_CategorySet();
        $categorySet->package = "test";
        $categorySet->title = 'testTitle';
        $categorySet->visible = true;

        $result = $this->service->create($categorySet);

        $this->assertInstanceOf('Content_Model_CategorySet_Interface', $result);
        return $result;
    }
    
    public function testCreateNullPackageCategorySet() {
        $categorySet = new Content_Model_CategorySet();
        $categorySet->package = null;
        $categorySet->title = 'testTitle';
        $categorySet->visible = true;
        $result = $this->service->create($categorySet);
        $this->assertInstanceOf('Content_Model_CategorySet_Interface', $result);
    }
    
    public function testCreateInvalidCategorySet() {
        $categorySet = new Content_Model_CategorySet();
        $categorySet->package = null;
        //$categorySet->title = 'testTitle';
        $categorySet->visible = true;
        $this->setExpectedException('Exception');
        $result = $this->service->create($categorySet);
    } 
    
    public function testCreateValidFromObject() {

        $result = $this->createValidObject();

        $this->assertNotNull($result->id);
        $this->assertEquals('test', $result->package);
        $this->assertEquals('testTitle', $result->title);
        $this->assertEquals(true, $result->visible);
    }
    
    public function testCreateFromArray() {

        $categorySet = array(
        'package' => 'test',
        'title' => 'testTitle',
        'visible' => false);

        $result = $this->service->create($categorySet);

        $this->assertInstanceOf('Content_Model_CategorySet_Interface', $result);

        $this->assertNotNull($result->id);
        $this->assertEquals('test', $result->package);
        $this->assertEquals('testTitle', $result->title);
        $this->assertEquals(false, $result->visible);
    }

    public function testCreateException() {
        $this->setExpectedException('InvalidArgumentException');

        $badObject = new StdClass();
        $create = $this->service->create($badObject);
    }

    public function testGetObjectById() {

        //setup
        $categorySet = $this->createValidObject();

        //test getObject
        $result = $this->service->getObjectById($categorySet->id);
        
        $this->assertInstanceOf('Content_Model_CategorySet_Interface', $result);

        $this->assertEquals($categorySet->id, $result->id);
        $this->assertEquals('test', $result->package);
        $this->assertEquals('testTitle', $result->title);
        $this->assertEquals(true, $result->visible);
    }

    public function testUpdateFromObject() {

        //setup
        $categorySet = $this->createValidObject();

        //update values
        $categorySet->package = "test2";
        $categorySet->title = 'testTitle2';
        $categorySet->visible = false;

        $result = $this->service->update($categorySet);

        $this->assertInstanceOf('Content_Model_CategorySet_Interface', $result);

        $this->assertEquals($categorySet->id, $result->id);
        $this->assertEquals('test2', $result->package);
        $this->assertEquals('testTitle2', $result->title);
        $this->assertEquals(false, $result->visible);
    }
    
    public function testUpdateFromArray() {

        //setup
        $categorySet = $this->createValidObject();

        $array = $categorySet->toArray();
        
        //update values
        $array['package'] = "test2";
        $array['title'] = 'testTitle2';
        $array['visible'] = false;

        $result = $this->service->update($array);

        $this->assertInstanceOf('Content_Model_CategorySet_Interface', $result);

        $this->assertEquals($categorySet->id, $result->id);
        $this->assertEquals('test2', $result->package);
        $this->assertEquals('testTitle2', $result->title);
        $this->assertEquals(false, $result->visible);
    }
    

    public function testUpdateException() {
        $this->setExpectedException('InvalidArgumentException');

        $badObject = new StdClass();
        $create = $this->service->update($badObject);
    }

    public function testDeleteObject() {

        //setup
        $categorySet = $this->createValidObject();

        //test delete
        $this->service->delete($categorySet);

        //verify that it was deleted
        $this->setExpectedException('NotFoundException');
        $result = $this->service->getObjectById($categorySet->id);
    }

    public function testDeleteId() {

        //setup
        $categorySet = $this->createValidObject();
       // $this->fail("id: ".$categorySet->id);
        $this->service->delete((int)$categorySet->id);
        
        $this->setExpectedException('NotFoundException');
        $result = $this->service->getObjectById($categorySet->id); 
    }
    
    public function testDeleteArray() {

        //setup
        $categorySet = $this->createValidObject();
       // $this->fail("id: ".$categorySet->id);
        $this->service->delete($categorySet->toArray());
        
        $this->setExpectedException('NotFoundException');
        $result = $this->service->getObjectById($categorySet->id); 
    }

    public function testDeleteException() {
        $this->setExpectedException('InvalidArgumentException');

        $badObject = new StdClass();
        $create = $this->service->delete($badObject);
    }

    public function testDeleteAll() {
//        $this->service->deleteAll();
    }

}