<?php echo $this->heading('Users'); 

$groupService = new Core_Model_Group_Service();
$groups = $groupService->getList();

?>

<div class="cms ui-widget ui-widget-content ui-corner-all">
<div class="ui-widget-content">
    <table width="100%">
        <thead class="ui-widget-header">
            <tr><th>Id</th><th>Primary Group</th><th>User</th><th>Name</th><th width="50"></th></tr>
        </thead>
        <tbody>
            <?php
            foreach ($this->objects as $object) {
                /* @var $object Content_Model_User */
            ?>
            <tr  class="<?php echo $this->cycle(array("", "ui-state-default"))->next() ?>" >
                <td><?php echo $object->id ?></td>
                <td><?php echo $groups[$object->primary_group] ?></td>
                <td><?php echo $object->username ?></td>
                <td><?php echo $object->name ?></td>
                <td>
                    <a class="button" data-text="false" data-icon="ui-icon-pencil" title="Edit User &quot;<?php echo $object->username ?>&quot;" 
                       href="<?php echo $this->url(array('controller' => 'user', 'id' => $object->id, 'action' => 'edit'), 'admin-id'); ?>">
                        Edit
                    </a> 
                    <a class="button"  data-text="false" data-icon="ui-icon-close" title="Delete User &quot;<?php echo $object->username ?>&quot;" 
                       href="<?php echo $this->url(array('controller' => 'user', 'id' => $object->id, 'action' => 'delete'), 'admin-id'); ?>">
                        Delete
                    </a>
                </td>
            </tr><?php
            }
            ?>
        </tbody>
    </table>
    <a class="button" data-icon="ui-icon-plusthick" href="<?php echo $this->url(array('controller' => 'user', 'action' => 'new'), 'admin'); ?>">New</a>
</div>
</div>