<h1><?php echo $this->roomName ?></h1>
<div class="homeNet-room-menu">
<a class="button"  href="<?php echo $this->url(array('house' => $this->house, 'room' => $this->room, 'region' => $this->region, 'node' => $this->node, 'action' => 'info'), 'homenet-room') ?>">Information</a>
<a class="ui-state-hover button" href="<?php echo $this->url(array('house' => $this->house, 'room' => $this->room, 'region' => $this->region, 'node' => $this->node, 'action' => 'control'), 'homenet-room') ?>">Control</a>
</div>
<?php
$timeCache = array();

foreach ($this->subdevices as $subdevice) {

    if (!$subdevice->hasControls()) {
        continue;
    }


?>
    <div class="ui-widget ui-state-default ui-corner-all homeNet-room-subdevice">
        <h2><?php echo $subdevice->name ?></h2>

        <div id="control-<?php echo $subdevice->id ?>" class="subdevice-graph" style="">
<?php echo $subdevice->getControlForm(); ?>

        </div>

</div>
<br />
    <?php
}
    ?>