<?php echo $this->heading($this->room->name); ?>
<div class="homeNet-room-menu">
<a class="button"  href="<?php echo $this->url(array('controller'=>'room', 'action' => 'info', 'house' => $this->house->id, 'id' => $this->id, ), 'homenet-house-id') ?>">Information</a>
<a class="ui-state-hover button" href="<?php echo $this->url(array('controller'=>'room', 'action' => 'control', 'house' => $this->house->id, 'id' => $this->id), 'homenet-house-id') ?>">Control</a></div>
<?php
$timeCache = array();

foreach ($this->components as $object) {

    if (!$object->hasControls()) {
        continue;
    }


?>
    <div class="ui-widget ui-state-default ui-corner-all homeNet-room-component">
        <h2><?php echo $object->name ?></h2>

        <div id="control-<?php echo $object->id ?>" class="component-graph" style="">
<?php echo $object->getControlForm(); ?>

        </div>

</div>
<br />
    <?php
}
    ?>