<?php echo $this->heading($this->room->name); ?>
<div class="homeNet-room-menu">
<a class="ui-state-hover button"  href="<?php echo $this->url(array('controller'=>'room', 'action' => 'info', 'house' => $this->house->id, 'id' => $this->id, ), 'homenet-house-id') ?>">Information</a>
<a class="button" href="<?php echo $this->url(array('controller'=>'room', 'action' => 'control', 'house' => $this->house->id, 'id' => $this->id), 'homenet-house-id') ?>">Control</a>
</div>
<?php
$timeCache = array();

foreach ($this->components as $component) {

    if (!$component->hasGraphs()) {
        continue;
    }

    $presets = $component->getGraphPresets();

    $first = reset($presets);

    if ($first['start'] instanceof Zend_Date) {
        $start = $first['start']->getTimestamp();
    } else {

        $timeCache[$first['start']] = strtotime($first['start']);
        $start2 = new Zend_Date($timeCache[$first['start']], Zend_Date::TIMESTAMP);
    }

    if ($first['end'] instanceof Zend_Date) {
        $end = $first['end']->getTimestamp();
    } else {
        $timeCache[$first['end']] = strtotime($first['end']);
        $end2 = new Zend_Date($timeCache[$first['end']], Zend_Date::TIMESTAMP);
    }

    $newest = $component->getNewestDataPoint();

    if(empty($newest)){
        $newest['value'] = '';
        $time = 'No Data Found';
    } else {
        $time = $newest['datetime']->get(Zend_Date::DATETIME_MEDIUM);
    }

   // die(debugArray($newest));

?>
    <div class="ui-widget ui-state-default ui-corner-all homeNet-room-subdevice">
        <h2><?php echo $component->name ?></h2>
        <div style="width:80px; float:left; margin-right: 10px;">
           <div class="homenet-room-newestvalue"><?php echo $newest['value'];  ?></div>
           <div class="homenet-room-lastupdate"><?php echo $time; ?></div>
            
        </div>

        <div id="graph-<?php echo $component->id ?>" class="" style="height:100px;">

            <img alt="graph" src="<?php echo $component->getGraph($start2, $end2); ?>" />
        </div>
<?php
$links = array();
    foreach ($presets as $key => $value) {

        if ($value['start'] instanceof Zend_Date) {
            $start = $value['start']->getTimestamp();
        } else {
            if (empty($timeCache[$value['start']])) {
                $timeCache[$value['start']] = strtotime($value['start']);
            }
            $start = $timeCache[$value['start']];
        }

        if ($value['end'] instanceof Zend_Date) {
            $end = $value['end']->getTimestamp();
        } else {
            if (empty($timeCache[$value['end']])) {
                $timeCache[$value['end']] = strtotime($value['end']);
            }
            $end = $timeCache[$value['end']];
        }


        $links[] = $this->ajaxLink($key,
                $this->url(array('controller'=>'component', 'action' => 'graph', 'house' => $this->house->id, 'id' => $component->id), 'homenet-house-id')."?start=$start&end=$end",
                array('update' => '#graph-' . $component->id));

    }
    echo implode(" &nbsp; ", $links);
?>
</div>
<br />
    <?php
}
    ?>
<a class="button" href="<?php echo $this->url(array('controller'=>'node', 'action'=>'new',     'house' => $this->house->id, 'room' => $this->id), 'homenet-house-room') ?>">Add Node</a>
<a class="button" href="<?php echo $this->url(array('controller'=>'room', 'action' => 'edit',  'house' => $this->house->id, 'id' => $this->id), 'homenet-house-id') ?>">Edit Room</a>
<a class="button" href="<?php echo $this->url(array('controller'=>'room', 'action' => 'delete','house' => $this->house->id, 'id' => $this->id), 'homenet-house-id') ?>">Remove Room</a>
