<h1><?php echo $this->controllerTitle ?></h1>
<table class="ui-widget" width="100%">
    <thead class="ui-widget-header">
        <tr><th>Id</th><th>Name</th><th>Path</th><th width="150">Edit/Delete</th></tr>
    </thead>
    <tbody class="ui-widget-content">
        <?php
        foreach ($this->objects as $object) { 
            /* @var $object Core_Model_Route */ 
            ?>
            <tr  class="<?php echo $this->cycle(array("", "ui-state-highlight"))->next() ?>" >
                <td><?php echo $object->id ?></td>
                <td><?php echo $object->name ?></td>
                <td><?php echo $object->path ?></td>
                <td><a href="<?php echo $this->url(array('controller' => 'route', 'id' => $object->id, 'action' => 'edit'), 'admin-route-id'); ?>">Edit</a> <a href="<?php echo $this->url(array('controller' => 'route', 'id' => $object->id, 'action' => 'delete'), 'admin-route-id'); ?>">Delete</a></td>
            </tr><?php
        }
        ?>
    </tbody>
</table>
<a class="button"  href="<?php echo $this->url(array('controller' => 'route', 'action' => 'new'), 'admin-route'); ?>">New</a>