<h1>Contact</h1>
<h2>Bugs/Feature Requests</h2>
<div class="transparent box">
<p>Please report bugs and feature requests over at <a href="http://code.google.com/p/homenet/issues/list">HomeNet Google Code site</a></p>
</div>

<h2>Send a message</h2>
<div class="transparent box">
<p><iframe src="https://spreadsheets.google.com/embeddedform?formkey=dDdtV3o0WXRwdDRVTDhVYi1vMVR2a2c6MQ"  width="580" height="630" frameborder="0" marginheight="0" marginwidth="0" style="overflow:hidden">Loading...</iframe></p>
</div>