

<section>
    <h2>Empowering your Open Source Smart House</h2>
    <p>HomeNet is a new way of thinking about home automation and "Smart Houses": DIY, Open, Free, and Collaborative.
        It's ideas that can be adapted to run on a variety of hardware platforms from simple Arduino microcontrollers to PCs.  HomeNet's goal is to
        unite all of your home's systems under one interface, that you can access from
        anywhere, from your pc, tablet or cell phone.</p>
    <p>Based on Open Source Arduino hardware, it's easy to integrate your existing devices or build your custom device. </p>

    <p>The dream of HomeNet is to one day link all of your home systems like: security system,
        smoke detectors, doorbell, home automation, lights, light switches, thermostats and more so that the devices become "smart" and can interact with each other.</p>

</section><br />
<!--</div>-->
<section>
<h2>Features</h2>

    <h3>Graphing</h3>
    <p class="center"><a href="http://www.flickr.com/photos/archicroc/5528837257/" title="HomeNet.me by ArchiCroc, on Flickr"><img src="http://farm6.static.flickr.com/5096/5528837257_d87b79ae71.jpg" width="360" height="148" alt="HomeNet.me" /></a></p>
    <p>Visualize your home in a new dimension. View environmental data, energy usage and more. Compare weeks, months years*</p>
    <br />

    <h3>Remote Control</h3>
    <p class="center"><a href="http://www.flickr.com/photos/archicroc/5528837277/" title="HomeNet.me by ArchiCroc, on Flickr"><img src="http://farm6.static.flickr.com/5056/5528837277_9ce2203880.jpg" width="360" height="57" alt="HomeNet.me" /></a></p>
    <p>Turn devices on and off remotely. Open and close blinds, lock and unlock doors*. The possibilities are endless</p>
    <br />

    <h3>Home Automation*</h3>
    <p>Link inputs like temperature sensors and light sensors to outputs like lamps, blinds and more</p>
    <p>Manually schedule devices to turn on and off, on a programmable schedule.</p>
    <br />

    <h3>Mobile Web App</h3>
    <p class="center"><a href="http://www.flickr.com/photos/archicroc/5533113980/" title="mobile by ArchiCroc, on Flickr"><img src="http://farm6.static.flickr.com/5173/5533113980_3b63d81dae.jpg" width="261" height="249" alt="mobile" /></a></p>
    <p><a href="http://m.HomeNet.me">http://m.HomeNet.me</a></p>
    <p>Check on your home on the go. View and control your home from your cell phone.</p>
    <br />

    <h3>Social Home*</h3>
    <p>Get alerts sent to you via text message, email, Facebook and Twitter</p>
    <p>Alerts can be sent when any issue is detected- security sensors tripped, windows left open, appliances malfunction, excessive energy usage, fire/carbon monoxide</p>
    <br />
    
    <h3>AutoCode Generation</h3>
    <p class="center"><a href="http://www.flickr.com/photos/archicroc/5528837291/" title="HomeNet.me by ArchiCroc, on Flickr"><img src="http://farm6.static.flickr.com/5136/5528837291_fffa877cdb.jpg" width="500" height="300" alt="HomeNet.me" /></a></p>
    <p>For some, programming an Arduino can be intimidating. HomeNet.me makes it easy by generating the code you need automatically.
        Already an Arduino user? HomeNet.me also offers code templates you can customize to add custom functionality.</p>
</section><br />
<section>
<h2>Hardware</h2>

    <h3>Arduino</h3>
    <p class="center"><a href="http://www.flickr.com/photos/archicroc/5248202447/" title="Arduino by ArchiCroc, on Flickr"><img src="http://farm6.static.flickr.com/5167/5248202447_7f6cd619dc_m.jpg" width="240" height="160" alt="Arduino" /></a></p>
    <p>All you need to get started is an Arduino. Connected it to your computer with the HomeNetApp and Upload Sensor data to the Internet</p>
    <br />
    <h3>JeeLabs: JeeNodes</h3>
    <p class="center"><a href="http://www.flickr.com/photos/archicroc/5379566120/" title="IMG_3981 by ArchiCroc, on Flickr"><img src="http://farm6.static.flickr.com/5121/5379566120_487d8a645a_m.jpg" width="240" height="160" alt="IMG_3981" /></a></p>
    <p>You can build an even bigger, and better HomeNet using JeeNodes from <a href="http://jeelabs.org">JeeLabs</a>. They are have an integrated wireless transmitter so you can have nodes all over your house.
        HomeNet.me makes it easy by managing your nodes and keeping track of the code required.</p>
    <br />
    <h3>Build your Own</h3>
    <p>HomeNet is Open Source. Use our software on what ever you dream up. The possibilities are endless</p>
    <br />

</section><br />
<section>
<h2>Project Status</h2>
<div class="transparent box">
    <p>The project is currently in a pre Alpha state. New features are being added at a rapid pace. </p>

    <p>I am working on getting a public demo up.
        <a href="https://spreadsheets.google.com/viewform?formkey=dHg4QjB0RzN0YkoybEVzd05qbXdxZnc6MQ">Let me know</a> if you want to see it sooner.</p>

    <p>Those who are interested giving HomeNet a try, <a href="https://spreadsheets.google.com/viewform?formkey=dHg4QjB0RzN0YkoybEVzd05qbXdxZnc6MQ">Request an access key</a></p>

</section><br />
<section>

<h2>Contribute</h2>

    <p>All of the HomeNet.me Code is licensed under the GPLv3</p>
    <p>

        The HomeNet.me project could greatly use the skills of some talented people. There are many area's where you can contribute-
        improve the Arduino Device drivers (c++), improve the Desktop App (Java), add new features to the web backend (PHP/Zend Framework)
        or enhance the front end (jQuery/jQueryUI).</p>
    <p>
        All of the HomeNet.me source code is avaliable on <a href="http://code.google.com/p/homenet/">Google Code</a>.
    </p>
</section><br />
<section>

<h2>Support</h2>

    <p>This is currently the Master Project of Matthew Doll, a graduate student at the University of South Florida.</p>

    <p> I'm am very interested in continuing work on this project after I graduate in the spring.</p>

    <p> I am currently looking for interest into creating a kickstarter.com campaign to launch a company around this site.
        Interested in helping out? <a href="https://spreadsheets.google.com/viewform?formkey=dHg4QjB0RzN0YkoybEVzd05qbXdxZnc6MQ">Let me know</a>!</p>

    <p> Another possibility is getting some grant money.  If you know of a grant I should pursue, <a href="/contact">I want to know</a>.
    </p>
    <p>Follow HomeNet.me on <a href="http://twitter.com/homenetme">Twitter</a> and <a href="http://www.facebook.com/pages/HomeNetme/140855362648347">Facebook</a>
    </p>
</section>

<p>*Planned Feature</p>