<?php

if(!empty($_POST)){
    echo debugArray($_POST);
}

?>
<form action="" method="post">
    <section>
    <h2>Select Gallery:</h2>
<?php
echo $this->formAjaxGallery('gallery', null, null, array(
    'rest'=>$this->url(array('controller'=>'content','action'=>'rest'),'content-admin'),
    'folder' => 'content/projects'));

?>
       </section>
    <section>
            <h2>Select Single Image:</h2>
<?php
echo $this->formAjaxImage('image', null, null, array(
    'rest'=>$this->url(array('controller'=>'content','action'=>'rest'),'content-admin'),
    'folder' => ''));

?>
        </section>
    
        <section>
            <h2>Wysiwyg Editor:</h2>
<?php
echo $this->formAjaxWysiwyg('content', null, null, array(
    'rest'=>$this->url(array('controller'=>'content','action'=>'rest'),'content-admin'),
    'folder' => ''));

?>
        </section>
    
    
    <input type="submit" value="submit">
</form>
 