<?php echo $this->heading($this->controllerTitle); ?>

<!--<p><a class="button"  href="<?php echo $this->url(array('controller' => 'admin', 'action' => 'index'), 'admin'); ?>">Back to Sets</a></p>-->

<table class="ui-widget" width="100%">
    <thead class="ui-widget-header">
        <tr><th width="50">ID</th><th>Name</th><th width="150">Edit/Delete</th></tr>
    </thead>
    <tbody class="ui-widget-content">
        <?php
        foreach ($this->objects as $object) {
            /* @var $object Content_Model_Category */
            ?>
            <tr  class="<?php echo $this->cycle(array("", "ui-state-highlight"))->next() ?>" >
                <td><?php echo $object->id ?></td>
                <td class="left"><a href="<?php echo $this->url(array('controller' => 'menu-item','id' => $object->id, 'action' => 'index'), 'admin-id'); ?>"><?php echo $object->title ?></a></td>
                <td><a href="<?php echo $this->url(array('controller' => 'menu','id' => $object->id, 'action' => 'edit'), 'admin-id'); ?>">Edit</a> <a href="<?php echo $this->url(array('controller' => 'menu','id' => $object->id, 'action' => 'delete'), 'admin-id'); ?>">Delete</a></td>
            </tr><?php
        }
        ?>
    </tbody>
</table>
<a class="button"  href="<?php echo $this->url(array('controller' => 'menu', 'action' => 'new'), 'admin'); ?>">New</a>
