<div data-role="page">
    <div data-role="header">
        <h1><?php echo $this->roomName ?></h1>
    </div>
<div data-role="navbar">
            <ul>
                    <li><a data-ajax="false" class="ui-btn-active" href="<?php echo $this->url(array('house' => $this->house, 'room' => $this->room, 'region' => $this->region, 'node' => $this->node, 'action' => 'info'), 'homenet-room') ?>/">Information</a></li>
                    <li><a data-ajax="false" href="<?php echo $this->url(array('house' => $this->house, 'room' => $this->room, 'region' => $this->region, 'node' => $this->node, 'action' => 'control'), 'homenet-room') ?>/">Control</a></li>
            </ul>
    </div>
    <div data-role="content">
        <?php
        $timeCache = array();

        foreach ($this->subdevices as $subdevice) {

            if (!$subdevice->hasGraphs()) {
                continue;
            }

            $presets = $subdevice->getGraphPresets();

            $first = reset($presets);

            if ($first['start'] instanceof Zend_Date) {
                $start = $first['start']->getTimestamp();
            } else {

                $timeCache[$first['start']] = strtotime($first['start']);
                $start2 = new Zend_Date($timeCache[$first['start']], Zend_Date::TIMESTAMP);
            }

            if ($first['end'] instanceof Zend_Date) {
                $end = $first['end']->getTimestamp();
            } else {
                $timeCache[$first['end']] = strtotime($first['end']);
                $end2 = new Zend_Date($timeCache[$first['end']], Zend_Date::TIMESTAMP);
            }

            $newest = $subdevice->getNewestDataPoint();
        ?>
            <div class="ui-body ui-body-b">
                <div style="float:right" class="homenet-room-newestvalue"><h2><?php echo $newest['value'] ?></h2></div>
                <h2><?php echo $subdevice->name ?></h2>
                
                <div class="homenet-room-lastupdate">Last Update: <?php echo $newest['datetime']->get(Zend_Date::DATETIME_MEDIUM) ?></div>
                <div id="graph-<?php echo $subdevice->id ?>" class="" style="height:100px;">

                    <img alt="graph" src="<?php echo $subdevice->getGraph($start2, $end2); ?>" />
                </div>
</div>
                <div data-role="navbar">
		<ul><li><?php //
            $links = array();
            foreach ($presets as $key => $value) {

                if ($value['start'] instanceof Zend_Date) {
                    $start = $value['start']->getTimestamp();
                } else {
                    if (empty($timeCache[$value['start']])) {
                        $timeCache[$value['start']] = strtotime($value['start']);
                    }
                    $start = $timeCache[$value['start']];
                }

                if ($value['end'] instanceof Zend_Date) {
                    $end = $value['end']->getTimestamp();
                } else {
                    if (empty($timeCache[$value['end']])) {
                        $timeCache[$value['end']] = strtotime($value['end']);
                    }
                    $end = $timeCache[$value['end']];
                }


                $links[] = $this->ajaxLink($key,
                                $this->url(array('house' => $this->house, 'subdevice' => $subdevice->id, 'action' => 'graph', 'start' => $start, 'end' => $end), 'homenet-subdevice-graph'),
                                array('update' => '#graph-' . $subdevice->id));
            }
            echo implode("</li><li>", $links);
?></li></ul>
	
        </div>
        <br />
<?php
        }
?>
    </div>

    <div data-role="footer">
        <h4>HomeNet.me</h4>
    </div>
</div>