<?php

require_once dirname(__FILE__) . '/../../../../../../application/modules/HomeNet/models/Apikey/XmlRpc.php';

/**
 * Test class for HomeNet_Model_Apikey_XmlRpc.
 * Generated by PHPUnit on 2011-12-02 at 18:56:11.
 */
class HomeNet_Model_Apikey_XmlRpcTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Zend_XmlRpc_Client 
     */
    protected $client;

    /**
     * @var HomeNet_Model_Apikey_Service 
     */
    protected $service;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->client = new Zend_XmlRpc_Client('http://localhost/xmlrpc.php?setenv=testing');
        $this->client->setSkipSystemLookup(true);
        $this->service = new HomeNet_Model_Apikey_Service;
        $this->service->deleteAll();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

//homenet.apikey.validate///////////////////////////////////////////////////////
    
    
    public function testValidate_valid_local() {

        $object = $this->service->createApikeyForHouse(1);
        
        $xmlrpc = new HomeNet_Model_Apikey_XmlRpc();
        $this->assertTrue($xmlrpc->validate($object->id));

    }

    public function testValidate_invalid_local() {
        $this->setExpectedException('InvalidArgumentException');
        $xmlrpc = new HomeNet_Model_Apikey_XmlRpc();
        $this->assertFalse($xmlrpc->validate('wrongformat'));
    }
    

    public function testValidate_valid_remote() {
        $object = $this->service->createApikeyForHouse(1);
        $result = $this->client->call('homenet.apikey.validate', array($object->id));
        $this->assertTrue($result);
    }

    public function testValidate_invalid_remote() {
        $result = $this->client->call('homenet.apikey.validate', array('589461d023d099a6a76a46f0a19b93819f7148fe'));
        $this->assertFalse($result);
    }
    
    public function testValidate_null_remote() {
        $this->setExpectedException('Exception');
        $result = $this->client->call('homenet.apikey.validate', array(''));
    }
    
    public function testValidate_invalidFormat_remote() {
        $this->setExpectedException('Exception');
        $result = $this->client->call('homenet.apikey.validate', array('wrongstring'));
    }
    
    
    
}