<h1>Add Node</h1>
<?php echo $this->form;

if($this->done){   ?>
<p>Successfully Added Device</p>

<p><a class="button" href="<?php
echo $this->url(array('house'=>$this->house,'room'=>$this->room, 'region'=>$this->region, 'node'=>$this->node, 'action'=>'configure'),'homenet-node');
 ?>">Add Devices</a> <a class="button" href="<?php
echo $this->url(array('house'=>$this->house,'room'=>$this->room, 'region'=>$this->region, 'node'=>$this->node,  'action'=>'generate'),'homenet-node');
 ?>">Done, Generate Code</a></p>
<?php } ?>