<h1>Configure Node</h1>

<table class="ui-widget" width="100%">
  <thead class="ui-widget-header">
    <tr><th width="30">Plug</th><th>Device</th><th width="150">Modify</th></tr>
    </thead>
    <tbody class="ui-widget-content">
<?php for($i = 1; $i <= $this->maxDevices; $i++){ ?>
<tr class="<?php echo $this->cycle(array("","ui-state-highlight"))->next()?>">
    <td><?php echo $i ?></td>
    <td><?php if(!empty($this->devices[$i])){
        echo $this->devices[$i]->modelName;
    } ?></td>
    
    <td><?php if(!empty($this->devices[$i])){ ?>

        <a class="button" href="<?php echo $this->url(array('house'=>$this->house, 'node'=>$this->node->id, 'position'=>$i, 'action'=>'edit'),'homenet-device'); ?>"><span class="ui-icon ui-icon-pencil"></span></a>
        <a class="button" href="<?php echo $this->url(array('house'=>$this->house, 'node'=>$this->node->id, 'position'=>$i, 'action'=>'remove'),'homenet-device'); ?>"><span class="ui-icon ui-icon-closethick"></span></a>

 <?php  } else { ?>
        <a class="button" href="<?php echo $this->url(array('house'=>$this->house, 'node'=>$this->node->id, 'position'=>$i, 'action'=>'add'),'homenet-device'); ?>"><span class="ui-icon ui-icon-star"></span></a>

    <?php } ?>
    </td>
</tr>
<?php } ?>
</tbody>
</table>
<a class="button" href="<?php echo $this->url(array('house'=>$this->house, 'node'=>$this->node->id, 'action'=>'code' ),'homenet-node'); ?>">Generate Code</a>