<h1>Category Sets</h1>
<table class="ui-widget" width="100%">
    <thead class="ui-widget-header">
        <tr><th width="50">Id</th><th>Title</th><th width="150">Edit/Delete</th></tr>
    </thead>
    <tbody class="ui-widget-content">
        <?php
        foreach ($this->objects as $object) {
            /* @var $object Content_Model_Category */
            ?>
            <tr  class="<?php echo $this->cycle(array("", "ui-state-highlight"))->next() ?>" >
                <td><?php echo $object->id ?></td>
                <td><a href="<?php echo $this->url(array('controller' => 'field-set', 'id' => $object->id), 'content-id'); ?>"><?php echo $object->title ?></a></td>
                <td><a href="<?php echo $this->url(array('controller' => 'field-set', 'id' => $object->id, 'action' => 'edit'), 'content-id'); ?>">Edit</a> <a href="<?php echo $this->url(array('controller' => 'field-set', 'id' => $object->id, 'action' => 'delete'), 'content-id'); ?>">Delete</a></td>
            </tr><?php
        }
        ?>
    </tbody>
</table>
<a class="button"  href="<?php echo $this->url(array('controller' => 'field-set', 'action' => 'new','id' => $this->id), 'content-id'); ?>">New</a>

<?php /*
 * <h1>Node List</h1>

<table class="ui-widget" width="100%">
  <thead class="ui-widget-header">
    <tr><th width="30">ID</th><th>Name</th><th>Description</th><th width="150">Edit/Delete</th></tr>
    </thead>
    <tbody class="ui-widget-content">
<?php foreach($this->nodes as $node){ ?>
<tr class="<?php echo $this->cycle(array("","ui-state-highlight"))->next()?>">
    <td><?php echo $node->node ?></td>
    <td><?php echo $node->modelName ?></td>
    <td><?php echo $node->description ?></td>
    <td><a class="button" href="<?php echo $this->url(array('house'=>$this->house, 'node'=>$node->id, 'action'=>'index'),'homenet-node'); ?>"><span class="ui-icon ui-icon-wrench"></span></a>
        <a class="button" href="<?php echo $this->url(array('house'=>$this->house, 'node'=>$node->id, 'action'=>'edit'),'homenet-node'); ?>"><span class="ui-icon ui-icon-pencil"></span></a>
        <a class="button" href="<?php echo $this->url(array('house'=>$this->house, 'node'=>$node->id, 'action'=>'remove'),'homenet-node'); ?>"><span class="ui-icon ui-icon-closethick"></span></a></td>
</tr>
<?php } ?>
</tbody>
</table>
<a class="button" href="<?php echo $this->url(array('house'=>$this->house),'homenet-node-add'); ?>">Add Node</a>
<a class="button" href="<?php echo $this->url(array('house'=>$this->house),'homenet-apikeys'); ?>">API Keys</a>
 * 
 */
