<?php echo $this->heading($this->heading); ?>

<div class="ui-widget-content buttonfix">
    <a class="button" data-icon="ui-icon-circle-arrow-w" href="<?php echo $this->url(array('controller' => 'field', 'action' => 'index', 'id'=>$this->id),'content-admin-id'); ?>">Back to Fields</a>
</div>

<div class="cms ui-widget ui-widget-content ui-corner-all">
<div class="ui-widget-content">
<table width="100%">
    <thead class="ui-widget-header">
        <tr><th width="50">Id</th><th>Title</th><th width="50"></th></tr>
    </thead>
    <tbody>
        <?php
        foreach ($this->objects as $object) {
            /* @var $object Content_Model_Category */
            ?>
            <tr  class="<?php echo $this->cycle(array("", "ui-state-default"))->next() ?>" >
                <td><?php echo $object->id ?></td>
                <td><?php echo $object->title ?></td>
                <td>
                    <a class="button" data-text="false" data-icon="ui-icon-pencil" title="Edit FieldSet &quot;<?php echo $object->title ?>&quot;" 
                       href="<?php echo $this->url(array('controller' => 'field-set', 'id' => $object->id, 'action' => 'edit'),'content-admin-id'); ?>">
                        Edit
                    </a> 
                    <a class="button" data-text="false" data-icon="ui-icon-close" title="Delete FieldSet &quot;<?php echo $object->title ?>&quot;" 
                       href="<?php echo $this->url(array('controller' => 'field-set', 'id' => $object->id, 'action' => 'delete'),'content-admin-id'); ?>">
                        Delete
                    </a>
               </td>
            </tr><?php
        }
        ?>
    </tbody>
</table>
<a class="button" data-icon="ui-icon-plusthick" href="<?php echo $this->url(array('controller' => 'field-set', 'action' => 'new','id' => $this->id),'content-admin-id'); ?>">New</a>
</div>
</div>

