<?php
/*
 * Copyright (c) 2011 Matthew Doll <mdoll at homenet.me>.
 *
 * This file is part of HomeNet.
 *
 * HomeNet is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * HomeNet is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with HomeNet.  If not, see <http://www.gnu.org/licenses/>.
 */
?><!doctype html>

<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7]> <html class="no-js ie6 oldie" lang="en"> <![endif]-->
<!--[if IE 7]>    <html class="no-js ie7 oldie" lang="en"> <![endif]-->
<!--[if IE 8]>    <html class="no-js ie8 oldie" lang="en"> <![endif]-->
<!-- Consider adding an manifest.appcache: h5bp.com/d/Offline -->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en"> <!--<![endif]-->
<head>
    <meta charset="utf-8">
    <?php echo $this->headTitle(); ?>
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Mobile viewport optimized: j.mp/bplateviewport -->
    <meta name="viewport" content="width=device-width,initial-scale=1">

    <!-- Place favicon.ico and apple-touch-icon.png in the root directory: mathiasbynens.be/notes/touch-icons -->

    <!-- CSS: implied media=all -->
    <!-- CSS concatenated and minified via ant build script-->

    
    <?php if (APPLICATION_ENV == 'production') { ?>
    <link rel="stylesheet" href="/css/base.css">
    <?php 
        } else { ?>
    <link rel="stylesheet" href="/css/base.css?v=<?php echo time(); ?>">
    <?php } ?>
    
    <link rel="stylesheet" href="//ajax.googleapis.com/ajax/libs/jqueryui/1.8/themes/smoothness/jquery-ui.css" type="text/css" media="all" />
    <link rel="stylesheet" href="/themes/homenet/css/style.css">
<?php
 echo $this->headLink();
?>
    <!-- end CSS-->

    <!-- More ideas for your <head> here: h5bp.com/d/head-Tips-->
    <script src="/js/libs/modernizr-2.0.6.min.js"></script> 
</head>

<body>  
    <header class="transparent">
    <div id="logo"><a href="/">HomeNet</a></div>
    <div id="user">
        <?php echo $this->widget('Core','Login'); ?>
    </div>
    <nav id="top-menu">
    <ul>
        <li><a href="/about">About</a></li>
        <li><a href="http://code.google.com/p/homenet/wiki/GettingStarted">Getting Started</a></li>
        <li><a href="http://code.google.com/p/homenet/wiki/Intro">Wiki</a></li>
        <li><a href="http://code.google.com/p/homenet/downloads/list">Downloads</a></li>
        <li><a href="http://groups.google.com/group/homenetme/">Discussion</a></li>
        <li><a href="http://homenetme.blogspot.com">Blog</a></li>
        <li><a href="/contact">Contact</a></li>
    </ul>
    </nav>
    </header> 