<?php
/*

<h1></h1>

<table class="ui-widget" width="100%">
  <thead class="ui-widget-header">
    <tr><th width="30">ID</th><th>Name</th><th>Description</th><th width="150">Edit/Delete</th></tr>
    </thead>
    <tbody class="ui-widget-content">
        
<?php foreach($this->models as $model){ ?>
<tr class="<?php echo $this->cycle(array("","ui-state-highlight"))->next()?>">
    <td><?php echo $model->id ?></td>
    <td><?php echo $type[$model->type].' '.$model->name ?></td>
    <td><?php echo $model->description ?></td>
    <td><a class="button" href="<?php echo $this->url(array('model'=>$model->id, 'action'=>'edit'),  'homenet-nodemodels-model'); ?>"><span class="ui-icon ui-icon-pencil"></span></a>
        <a class="button" href="<?php echo $this->url(array('model'=>$model->id, 'action'=>'remove'),'homenet-nodemodels-model'); ?>"><span class="ui-icon ui-icon-closethick"></span></a></td>
</tr>
<?php } ?>
</tbody>
</table>
<a class="button" href="<?php echo $this->url(array('action'=>'add'),'homenet-nodemodels'); ?>">Add Node Model</a>
*/ ?>

<?php echo $this->heading('Node Models'); ?>
<?php $type = array(1 => 'Sensor Node', 2 => 'Base Station', 3 => 'Internet Node'); ?>
<div class="cms ui-widget ui-widget-content ui-corner-all">
<div class="ui-widget-content">
<table width="100%">
    <thead class="ui-widget-header">
        <tr><th width="50">ID</th><th>Type</th><th>Name</th><th>Description</th><th width="55"></th></tr>
    </thead>
    <tbody>
        <?php
        foreach ($this->objects as $object) {
            /* @var $object Content_Model_Category */
        ?>
        <tr  class="<?php echo $this->cycle(array("", "ui-state-default"))->next() ?>" >
            <td><?php echo $object->id ?></td>
            <td><?php echo $type[$object->type] ?></td>
            <td class="left"><?php echo $object->name ?></td>
            
            <td class="left"><?php echo $object->description ?></td>
            <td>
                <a class="button" data-text="false" data-icon="ui-icon-pencil" title="Edit NodeModel &quot;<?php echo $object->name ?>&quot;" 
                   href="<?php echo $this->url(array('controller' => 'node-model', 'id' => $object->id, 'action' => 'edit'),'homenet-admin-id'); ?>">
                    Edit
                </a> 
                <a class="button" data-text="false" data-icon="ui-icon-close" title="Delete NodeModel &quot;<?php echo $object->name ?>&quot;" 
                   href="<?php echo $this->url(array('controller' => 'node-model', 'id' => $object->id, 'action' => 'delete'),'homenet-admin-id'); ?>">
                    Delete
                </a>
           </td>
        </tr>
        <?php
        }
        ?>
    </tbody>
</table>
<a class="button" data-icon="ui-icon-plusthick" title="New NodeModel" href="<?php echo $this->url(array('controller' => 'node-model', 'action' => 'new'),'homenet-admin'); ?>">New</a>
</div>
</div>