<!doctype html>

<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7]> <html class="no-js ie6 oldie" lang="en"> <![endif]-->
<!--[if IE 7]>    <html class="no-js ie7 oldie" lang="en"> <![endif]-->
<!--[if IE 8]>    <html class="no-js ie8 oldie" lang="en"> <![endif]-->
<!-- Consider adding an manifest.appcache: h5bp.com/d/Offline -->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en"> <!--<![endif]-->
<head>
    <meta charset="utf-8">
    <?php echo $this->headTitle(); ?>
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Mobile viewport optimized: j.mp/bplateviewport -->
    <meta name="viewport" content="width=device-width,initial-scale=1">

    <!-- Place favicon.ico and apple-touch-icon.png in the root directory: mathiasbynens.be/notes/touch-icons -->

    <!-- CSS: implied media=all -->
    <!-- CSS concatenated and minified via ant build script-->

    
    <?php if (APPLICATION_ENV == 'production') { ?>
    <link rel="stylesheet" href="/css/base.css">
    <?php 
        } else { ?>
    <link rel="stylesheet" href="/css/base.css?v=<?php echo time(); ?>">
    <?php } ?>
    
    <link rel="stylesheet" href="//ajax.googleapis.com/ajax/libs/jqueryui/1.8/themes/smoothness/jquery-ui.css" type="text/css" media="all" />
<?php
 echo $this->headLink();
?>
    <!-- end CSS-->

    <!-- More ideas for your <head> here: h5bp.com/d/head-Tips-->
    <script src="/js/libs/modernizr-2.0.6.min.js"></script> 
</head>

<body>  
    <header>
        <h1><a href="/">Matthew Doll</a></h1>
        <?php echo $this->widget('Core','Login'); ?>
    </header>
    <nav>
        <ul>
            <li><a href="/bio">Bio</a></li>
            <li><a href="/projects/category/web.design">Web Design</a></li>
            <li><a href="/projects/category/architecture">Architecture</a></li>
            <li><a href="/projects/category/programming">Programming</a></li>     
            <li><a href="/projects/category/electronics">Electronics</a></li>
            <li><a href="/projects/category/photography">Photography</a></li>
            <!--<li><a href="/projects/category/everything.else">Everything Else</a></li>-->
        </ul>
    </nav>
    <aside>
        <ul>
            <li><a href="http://facebook.com/mdoll"><img src="/img/social/16/facebook.png" alt="Facebook"/></a></li>
            <li><a href="http://twitter.com/archicroc"><img src="/img/social/16/twitter.png" alt="Twiiter"/></a></li> 
            <li><a href="http://www.flickr.com/photos/archicroc"><img src="/img/social/16/flickr.png" alt="Flickr"/></a></li>
            <li><a href="http://www.youtube.com/user/crocodolljr"><img src="/img/social/16/youtube.png" alt="YouTube"/></a> </li>
            <li><a href="https://plus.google.com/105807368292490700748/"><img src="/img/social/16/google-plus.png" alt="Google+"/></a> </li>
            <li><a href="https://github.com/ArchiCroc"><img src="/img/social/16/github.png" alt="GitHub"/></a> </li>
            <li><a href="/contact"><img src="/img/social/16/email.png" alt="Email" /></a></li> 
        </ul>
    </aside>
    <div id="main">
