<?php

/**
 * Test class for HomeNet_IndexController.
 * Generated by PHPUnit on 2012-04-27 at 14:47:32.
 */
class HomeNet_IndexControllerTest extends CMS_Test_PHPUnit_ControllerTestCase {

    private $installer;
    private $homenetInstaller;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
       $this->installer = new Core_Installer();
        $this->installer->installTest();
        $this->installer->loginAsSuperAdmin();
        
        $this->homenetInstaller = new HomeNet_Installer();
        
        
        $this->bootstrap = new Zend_Application('testing', APPLICATION_PATH . '/configs/application.ini'); //
        $this->view = Zend_Registry::get('view');
     
       

        //$this->service = new Content_Model_Category_Service();
        parent::setUp();
        
        $request = $this->getRequest();
        $this->setModule('HomeNet');
        $this->setController('Index');
    }
   


    public function testIndexAction_noHouses() {
        //setup
        $this->homenetInstaller->uninstallTest();
        
        $this->setAction('Index');

        //run
        $this->dispatch();

        $this->assertACM();
    }
    
    
    /**
     * @todo Implement testIndexAction().
     */
    public function testIndexAction_house() {
        //setup
        $this->homenetInstaller->installTest(array('house','room'));
        
        $this->setAction('Index');

        //run
        $this->dispatch();

        $this->assertACM('Home');
    }

    /**
     * @todo Implement testSendPacketAction().
     */
    public function testSendPacketAction() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testHomeAction().
     */
    public function testHomeAction() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}