<?php echo $this->heading('Group Permissions'); 
$types = array('Core','System','Custom');
?>

<div class="cms ui-widget ui-widget-content ui-corner-all">
<div class="ui-widget-content">
    <table width="100%">
        <thead class="ui-widget-header">
            <tr><th>Id</th><th>Module</th><th>Controller</th><th>Action</th><th>Object</th><th>Permission</th><th width="50"></th></tr>
        </thead>
        <tbody>
            <?php
            foreach ($this->objects as $object) {
                /* @var $object Content_Model_Category */
            ?>
            <tr  class="<?php echo $this->cycle(array("", "ui-state-default"))->next() ?>" >
                <td><?php echo $object->id ?></td>
                <td><?php echo $object->module?$object->module:'-All-' ?></td>
                <td><?php echo $object->controller?$object->controller:'-All-' ?></td>
                <td><?php echo $object->action?$object->action:'-All-' ?></td>
                <td><?php echo $object->object?$object->object:'-All-' ?></td>
                <td><?php echo $object->permission?'Allow':'Deny'; ?></td>
                <td>
                    <a class="button" data-text="false" data-icon="ui-icon-pencil" title="Edit Permission" 
                       href="<?php echo $this->url(array('controller' => 'group-permission', 'id' => $object->id, 'action' => 'edit'), 'admin-id'); ?>">
                        Edit
                    </a> 
                    <a class="button"  data-text="false" data-icon="ui-icon-close" title="Delete Permission" 
                       href="<?php echo $this->url(array('controller' => 'group-permission', 'id' => $object->id, 'action' => 'delete'), 'admin-id'); ?>">
                        Delete
                    </a>
                </td>
            </tr><?php
            }
            ?>
        </tbody>
    </table>
    <a class="button" data-icon="ui-icon-plusthick" href="<?php echo $this->url(array('controller' => 'group-permission', 'action' => 'new','id' => $this->id), 'admin-id'); ?>">New</a>
</div>
</div>