<?php

require_once dirname(__FILE__) . '/../../../../../../../application/modules/Content/plugins/templates/Pages/Installer.php';

/**
 * Test class for Content_Plugin_Template_Pages_Installer.
 * Generated by PHPUnit on 2011-09-09 at 21:32:03.
 */
class Content_Plugin_Template_Pages_InstallerTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Content_Plugin_Template_Pages_Installer
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Content_Plugin_Template_Pages_Installer;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @todo Implement testGetName().
     */
    public function testMetadata() {   
        $this->assertTrue(is_string($this->object->getName()));
        $this->assertInstanceOf('Zend_Date', $this->object->getDate());
        $this->assertTrue(is_string($this->object->getVersion()));
        $this->assertTrue(is_string($this->object->getPublisher()));
        $this->assertTrue(is_string($this->object->getPublisherUrl()));
        $this->assertTrue(is_string($this->object->getSupportUrl()));
        
    }

}