<h1>Feed</h1>
<?php foreach ($this->alerts as $alert){ 
    switch ($alert->level){
        case HomeNet_Model_Message::ERROR:
            $class = 'ui-state-error';
            $icon = 'ui-icon-alert';
            break;
        case HomeNet_Model_Message::WARNING:
            $class = 'ui-state-error';
            $icon = 'ui-icon-alert';
            break;
        case HomeNet_Model_Message::INFO:
            $class = 'ui-state-highlight';
            $icon = 'ui-icon-info';
            break;
        case HomeNet_Model_Message::CHANGE:
            $class = 'ui-state-highlight';
            $icon = 'ui-icon-info';
            break;
        case HomeNet_Model_Message::NEWITEM:
            $class = 'ui-state-highlight';
            $icon = 'ui-icon-star';
            break;
        case HomeNet_Model_Message::HIGH:
            $class = 'ui-state-highlight';
            $icon = 'ui-icon-circle-arrow-n';
            break;
        case HomeNet_Model_Message::LOW:
            $class = 'ui-state-highlight';
            $icon = 'ui-icon-circle-arrow-s';
            break;
    }
    
    
    ?>
<div class="ui-widget">
				<div style="margin-bottom: 8px; padding: 0pt 0.7em;" class="<?php echo $class ?> ui-corner-all">
					<p>

                                            <span style="float: left; margin-right: 0.3em;" class="ui-icon <?php echo $icon ?>"></span>
					<?php echo $alert->message ?></p>
				</div>
			</div>
<?php } ?>