<?php /*
<h1>Device Models</h1>

<table class="ui-widget" width="100%">
  <thead class="ui-widget-header">
    <tr><th width="30">ID</th><th>Category</th><th>Name</th><th>Description</th><th width="150">Edit/Delete</th></tr>
    </thead>
    <tbody class="ui-widget-content">
<?php



foreach($this->models as $model){ ?>

<tr class="<?php echo $this->cycle(array("","ui-state-highlight"))->next()?>">
    <td><?php echo $model->id ?></td>
    <td><?php echo $categories[$model->category] ?></td>
    <td><?php echo $model->name ?></td>
    <td><?php echo $model->description ?></td>
    <td><a class="button" href="<?php echo $this->url(array('model'=>$model->id, 'action'=>'edit'),'homenet-devicemodels-model'); ?>"><span class="ui-icon ui-icon-pencil"></span></a>
        <a class="button" href="<?php echo $this->url(array('model'=>$model->id, 'action'=>'remove'),'homenet-devicemodels-model'); ?>"><span class="ui-icon ui-icon-closethick"></span></a></td>
</tr>
<?php } ?>
</tbody>
</table>
<a class="button" href="<?php echo $this->url(array('action'=>'add'),'homenet-devicemodels'); ?>">Add Device Model</a>
*/ ?>
<?php echo $this->heading('Device Models'); ?>
<?php $type = array(1 => 'Sensor Node', 2 => 'Base Station', 3 => 'Internet Node'); ?>
<div class="cms ui-widget ui-widget-content ui-corner-all">
<div class="ui-widget-content">
<table width="100%">
    <thead class="ui-widget-header">
        <tr><th width="50">ID</th><th>Category</th><th>Name</th><th>Description</th><th width="55"></th></tr>
    </thead>
    <tbody>
        <?php
        foreach ($this->objects as $object) {
            /* @var $object HomeNet_Model_DeviceModel */
        ?>
        <tr  class="<?php echo $this->cycle(array("", "ui-state-default"))->next() ?>" >
            <td><?php echo $object->id ?></td>
            <td><?php echo $this->categories[$object->category] ?></td>
            <td class="left"><?php echo $object->name ?></td>
            <td class="left"><?php echo $object->description ?></td>
            <td>
                <a class="button" data-text="false" data-icon="ui-icon-pencil" title="Edit DeviceModel &quot;<?php echo $object->name ?>&quot;" 
                   href="<?php echo $this->url(array('controller' => 'device-model', 'id' => $object->id, 'action' => 'edit'),'homenet-admin-id'); ?>">
                    Edit
                </a> 
                <a class="button" data-text="false" data-icon="ui-icon-close" title="Delete DeviceModel &quot;<?php echo $object->name ?>&quot;" 
                   href="<?php echo $this->url(array('controller' => 'device-model', 'id' => $object->id, 'action' => 'delete'),'homenet-admin-id'); ?>">
                    Delete
                </a>
           </td>
        </tr>
        <?php
        }
        ?>
    </tbody>
</table>
<a class="button" data-icon="ui-icon-plusthick" title="New DeviceModel" href="<?php echo $this->url(array('controller' => 'device-model', 'action' => 'new'),'homenet-admin'); ?>">New</a>
</div>
</div>