<?php echo $this->heading('Configure Node'); 
//$rooms = $this->house->getRoomList();
?>

<div class="cms ui-widget ui-widget-content ui-corner-all">
<div class="ui-widget-content">
<table width="100%">
    <thead class="ui-widget-header">
        <tr><th width="30">Plug</th><th>Device</th><th width="55"></th></tr>
    </thead>
    <tbody>
       <?php for($i = 1; $i <= $this->maxDevices; $i++){ ?>
        <tr  class="<?php echo $this->cycle(array("", "ui-state-default"))->next() ?>" >
            <td><?php echo $i ?></td>
            <?php if(!empty($this->devices[$i])){
                $object = $this->devices[$i];
                /*<th>Room</th><td><?php echo $rooms[$object->room]; ?></td>*/
            ?>
            
            <td><?php echo $object->model_name; ?></td>
            <td>
                <a class="button" data-text="false" data-icon="ui-icon-pencil" title="Edit Device &quot;<?php echo $i ?>&quot;" 
                   href="<?php echo $this->url(array('controller' => 'device', 'action' => 'edit', 'house' => $this->house->id, 'node' => $this->node->address, 'id' => $object->position),'homenet-house-node-id'); ?>">
                    Edit
                </a> 
                <a class="button" data-text="false" data-icon="ui-icon-close" title="Delete Node &quot;<?php echo $i ?>&quot;" 
                   href="<?php echo $this->url(array('controller' => 'device', 'action' => 'delete', 'house' => $this->house->id, 'node' => $this->node->address, 'id' => $object->position),'homenet-house-node-id'); ?>">
                    Delete
                </a>
            </td>
            <?php  } else { ?>
            <td></td>
            <td>
                 <a class="button" data-text="false" data-icon="ui-icon-plus" title="New Node &quot;<?php echo $i ?>&quot;" 
                   href="<?php echo $this->url(array('controller' => 'device', 'action' => 'new', 'house' => $this->house->id, 'node' => $this->node->address),'homenet-house-node'); ?>?position=<?php echo $i; ?>">
                    New
                </a>
            </td>
            <?php } ?>
        </tr>
        <?php
        }
        ?>
    </tbody>
</table>
<a class="button" data-icon="ui-icon-gear" title="Generate Code" 
   href="<?php echo $this->url(array('controller' => 'node', 'action' => 'code', 'house' => $this->house->id, 'id'=>$this->node->address),'homenet-house-id'); ?>">Generate Code</a>
</div>
</div>
<a class="button" data-icon="ui-icon-trash" title="View Trashed Nodes" 
   href="<?php echo $this->url(array('controller' => 'device', 'action' => 'trashed', 'house' => $this->house->id, 'node' => $this->node->address),'homenet-house-node'); ?>">Trashed Devices</a>