<?php
/*
 * Copyright (c) 2011 Matthew Doll <mdoll at homenet.me>.
 *
 * This file is part of HomeNet.
 *
 * HomeNet is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * HomeNet is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with HomeNet.  If not, see <http://www.gnu.org/licenses/>.
 */
?>
<footer>
(c) 2010 Matthew Doll http://mcdportal.com | Background Image by <a href="http://www.flickr.com/photos/wonderlane/4670429913/">wonderlane</a>
</footer>

<?php /*
  <!-- Grab Google CDN's jQuery, with a protocol relative URL; fall back to local if offline -->
  <script src="//ajax.googleapis.com/ajax/libs/jquery/1.6.2/jquery.min.js"></script>
  <script>window.jQuery || document.write('<script src="js/libs/jquery-1.6.2.min.js"><\/script>')</script>
*/ 
?>
    <?php 
       // $this->jQuery()->setVersion('1.7.1');
       // $this->jQuery()->useCdn();
        //$this->jQuery()->uiEnable();
        //$this->jQuery()->setUiVersion('1.8.16');
        //$this->jQuery()->useUiCdn();
        
        $this->jquery()->addOnLoad('$( ".button" ).simplebutton();
            $( \'input[type="submit"]"\' ).button();');
        
        $this->jQuery()->setRenderMode(15);
        //<script src="//ajax.googleapis.com/ajax/libs/jqueryui/1.8.16/jquery-ui.js"></script>
   ?>

<?php echo $this->jQuery(); ?>

    <script>window.jQuery || document.write('<script src="/js/libs/jquery-1.6.2.min.js"><\/script>')</script>
<?php 

 $this->headScript()->appendFile('/js/mylibs/jquery.simplebutton.js');

 echo $this->headScript();
?>
   
    <!-- scripts concatenated and minified via ant build script-->
    <script defer src="/js/plugins.js"></script>
    <script defer src="/js/script.js"></script>
    <!-- end scripts-->
    <?php 
$this->jQuery()->setRenderMode(16);

echo $this->jQuery();   /* ?>

     <!-- Change UA-XXXXX-X to be your site's ID
    <script>
    window._gaq = [['_setAccount','UA-19971497-2'],['_trackPageview'],['_trackPageLoadTime']];
    Modernizr.load({
      load: ('https:' == location.protocol ? '//ssl' : '//www') + '.google-analytics.com/ga.js'
    });
    </script>--> 
    <!--[if lt IE 7 ]>
    <script src="//ajax.googleapis.com/ajax/libs/chrome-frame/1.0.3/CFInstall.min.js"></script>
    <script>window.attachEvent('onload',function(){CFInstall.check({mode:'overlay'})})</script>
    <![endif]-->
 * 
 * 
 */ 
 //*/
 ?>
</body>
</html>
