<?php echo $this->heading($this->controllerTitle); ?>

<p><a class="button"  href="<?php echo $this->url(array('controller' => 'section', 'action' => 'index'),'content-admin'); ?>">Back to Section</a></p>

<table class="ui-widget" width="100%">
    <thead class="ui-widget-header">
        <tr><th width="50">Id</th><th width="200">Revision</th><th>Title</th> <th width="150">Edit/Delete</th></tr>
    </thead>
    <tbody class="ui-widget-content">
        <?php
        foreach ($this->objects as $object) {
            /* @var $object Content_Model_Category */
            ?>
            <tr  class="<?php echo $this->cycle(array("", "ui-state-highlight"))->next() ?>" >
                <td class="left"><?php echo $object->id ?></td>
                <td><?php echo $object->revision ?></td>
                <td class="left"><?php echo $object->title ?></td>
                <td><a href="<?php echo $this->url(array('controller' => 'content', 'id' => $object->id, 'action' => 'edit'),'content-admin-id'); ?>">Edit</a> <a href="<?php echo $this->url(array('controller' => 'content', 'id' => $object->id, 'action' => 'delete'),'content-admin-id'); ?>">Delete</a></td>
            </tr><?php
        }
        ?>
    </tbody>
</table>
<a class="button"  href="<?php echo $this->url(array('controller' => 'content', 'id' => $this->id, 'action' => 'new'),'content-admin-id'); ?>">New</a>