<?php

//require_once dirname(__FILE__) . '/../../../../../../application/modules/Content/models/Section/Field/Service.php';

/**
 * Test class for Content_Model_SectionField_Service.
 * Generated by PHPUnit on 2011-06-22 at 08:14:24.
 */
class Content_Model_Field_ServiceTest extends PHPUnit_Framework_TestCase {

   /**
     * @var Content_Model_Field_Service
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Content_Model_Field_Service();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
       $this->object->deleteAll();
    }

    public function testGetMapper() {

        $this->assertInstanceOf('Content_Model_Field_MapperInterface', $this->object->getMapper());
    }

    /**
     * @todo Implement testSetMapper().
     */
    public function testSetMapper() {
        
        $mapper = new Content_Model_Field_MapperDbTable();
         $this->object->setMapper($mapper);
        
        $this->assertInstanceOf('Content_Model_Field_MapperInterface', $this->object->getMapper());
        $this->assertEquals($mapper, $this->object->getMapper());
        //$this->ass
    }
    
    private function createValidSectionField() {
        $field = new Content_Model_Field();
        $field->section = 1;
        $field->order = 2;
        $field->element = 'text';
        $field->name = 'testName';
        $field->name_label = 'testLabel';
        $field->default_value = 'testValue';
        $field->attributes = array('testA'=>'valueA');
        $field->validators = array('testB'=>'valueB');
        $field->filters = array('testC'=>'valueC');
        $field->locked = false;
        $field->type = 0;
        $field->required = false;
        $field->visible = true;

        $result = $this->object->create($field);

        $this->assertInstanceOf('Content_Model_Field_Interface', $result);
        return $result;
    }
    
    public function testCreateInvalidSectionField() {
        $field = new Content_Model_Field();
        $field->section = 1;
        $field->order = 2;
        //$field->name = 'testName';
        $field->element = 'text';
        $field->name_label = 'testLabel';
        $field->default_value = 'testValue';
        $field->attributes = array('testA'=>'valueA');
        $field->validators = array('testB'=>'valueB');
        $field->filters = array('testC'=>'valueC');
        $field->locked = false;
        $field->type = 0;
        $field->required = false;
        $field->visible = true;
        $this->setExpectedException('Exception');
        $result = $this->object->create($field);
    }
//    
//    public function testDuplicateUrl() {
//
//        $field1 = $this->createValidSectionField();
//        $this->setExpectedException('DuplicateEntryException');
//        $field2 = $this->createValidSectionField();
//    }

    public function testCreateValidFromObject() {

        $result = $this->createValidSectionField();       

        $this->assertNotNull($result->id);
        $this->assertEquals(1, $result->section);
        $this->assertEquals(2, $result->order);
        $this->assertEquals('text', $result->element);
        $this->assertEquals('testName', $result->name);
        $this->assertEquals('testLabel', $result->name_label);
        $this->assertEquals('testValue', $result->default_value);
        $this->assertEquals('valueA', $result->attributes['testA']);
        $this->assertEquals('valueB', $result->validators['testB']);
        $this->assertEquals('valueC', $result->filters['testC']);
        $this->assertEquals(false, $result->locked);
        $this->assertEquals(0, $result->type);
        $this->assertEquals(false, $result->required);
        $this->assertEquals(true, $result->visible);
    }
    
    public function testCreateFromArray() {

        $field = array(
            'section' => 1,
            'order' => 2,
            'element' => 'text',
            'name' => 'testName',
            'name_label' => 'testLabel',
            'default_value' => 'testValue',
            'attributes' => array('testA' => 'valueA'),
            'validators' => array('testB' => 'valueB'),
            'filters' => array('testC' => 'valueC'),
            'locked' => false,
            'type' => 0,
            'required' => false,
            'visible' => true);

        $result = $this->object->create($field);

        $this->assertInstanceOf('Content_Model_Field_Interface', $result);

         $this->assertNotNull($result->id);
        $this->assertEquals(1, $result->section);
        $this->assertEquals(2, $result->order);
        $this->assertEquals('text', $result->element);
        $this->assertEquals('testName', $result->name);
        $this->assertEquals('testLabel', $result->name_label);
        $this->assertEquals('testValue', $result->default_value);
        $this->assertEquals('valueA', $result->attributes['testA']);
        $this->assertEquals('valueB', $result->validators['testB']);
        $this->assertEquals('valueC', $result->filters['testC']);
        $this->assertEquals(false, $result->locked);
        $this->assertEquals(0, $result->type);
        $this->assertEquals(false, $result->required);
        $this->assertEquals(true, $result->visible);
    }

    public function testCreateException() {
        $this->setExpectedException('InvalidArgumentException');

        $badObject = new StdClass();
        $create = $this->object->create($badObject);
    }

    public function testGetObjectById() {

        //setup
        $field = $this->createValidSectionField();

        //test getObject
        $result = $this->object->getObjectById($field->id);
        
        $this->assertInstanceOf('Content_Model_Field_Interface', $result);
        
        $this->assertEquals($field->id, $result->id);
        $this->assertEquals(1, $result->section);
        $this->assertEquals(2, $result->order);
        $this->assertEquals('text', $result->element);
        $this->assertEquals('testName', $result->name);
        $this->assertEquals('testLabel', $result->name_label);
        $this->assertEquals('testValue', $result->default_value);
        $this->assertEquals('valueA', $result->attributes['testA']);
        $this->assertEquals('valueB', $result->validators['testB']);
        $this->assertEquals('valueC', $result->filters['testC']);
        $this->assertEquals(false, $result->locked);
        $this->assertEquals(0, $result->type);
        $this->assertEquals(false, $result->required);
        $this->assertEquals(true, $result->visible);
    }
    
//    public function testGetObjectByUrl() {
//
//        //setup
//        $field = $this->createValidSectionField();
//
//        //test getObject
//        $result = $this->object->getObjectByUrl($field->url);
//        
//        $this->assertInstanceOf('Content_Model_Field_Interface', $result);
//
//        $this->assertEquals($field->id, $result->id);
//        $this->assertEquals(0, $result->set);
//        $this->assertEquals(1, $result->parent);
//        $this->assertEquals(2, $result->order);
//        $this->assertEquals('testUrl', $result->url);
//        $this->assertEquals('testTitle', $result->title);
//        $this->assertEquals('testDescription', $result->description);
//    }
//    
//     public function testGetInvalidObjectByUrl() {
//
//        $this->setExpectedException('NotFoundException');
//        $result = $this->object->getObjectByUrl("testnotindatabase");
//
//    }

    public function testUpdateFromObject() {

        //setup
        $field = $this->createValidSectionField();

        //update values
        $field->section = 2;
        $field->order = 3;
        $field->element = 'textarea';
        $field->name = 'testName2';
        $field->name_label = 'testLabel2';
        $field->default_value = 'testValue2';
        $field->attributes = array('testA'=>'valueA2');
        $field->validators = array('testB'=>'valueB2');
        $field->filters = array('testC'=>'valueC2');
        $field->locked = true;
        $field->type = 0;
        $field->required = true;
        $field->visible = false;

        $result = $this->object->update($field);

        $this->assertInstanceOf('Content_Model_Field_Interface', $result);
        $this->assertEquals($field->id, $result->id);
        $this->assertEquals(2, $result->section);
        $this->assertEquals(3, $result->order);
        $this->assertEquals('textarea', $result->element);
        $this->assertEquals('testName2', $result->name);
        $this->assertEquals('testLabel2', $result->name_label);
        $this->assertEquals('testValue2', $result->default_value);
        $this->assertEquals('valueA2', $result->attributes['testA']);
        $this->assertEquals('valueB2', $result->validators['testB']);
        $this->assertEquals('valueC2', $result->filters['testC']);
        $this->assertEquals(true, $result->locked);
        $this->assertEquals(0, $result->type);
        $this->assertEquals(true, $result->required);
        $this->assertEquals(false, $result->visible);
    }
    
    public function testUpdateFromArray() {

        //setup
        $field = $this->createValidSectionField();

        $array = $field->toArray();
        
        //update values
        $array['section'] = 2;
        $array['order'] = 3;
        $array['element'] = 'textarea';
        $array['name'] = 'testName2';
        $array['name_label'] = 'testLabel2';
        $array['default_value'] = 'testValue2';
        $array['attributes'] = array('testA'=>'valueA2');
        $array['validators'] = array('testB'=>'valueB2');
        $array['filters'] = array('testC'=>'valueC2');
        $array['locked'] = true;
        $array['type'] = 0;
        $array['required'] = true;
        $array['visible'] = false;


        $result = $this->object->update($array);

        $this->assertInstanceOf('Content_Model_Field_Interface', $result);
        $this->assertEquals($field->id, $result->id);
        $this->assertEquals(2, $result->section);
        $this->assertEquals(3, $result->order);
        $this->assertEquals('textarea', $result->element);
        $this->assertEquals('testName2', $result->name);
        $this->assertEquals('testLabel2', $result->name_label);
        $this->assertEquals('testValue2', $result->default_value);
        $this->assertEquals('valueA2', $result->attributes['testA']);
        $this->assertEquals('valueB2', $result->validators['testB']);
        $this->assertEquals('valueC2', $result->filters['testC']);
        $this->assertEquals(true, $result->locked);
        $this->assertEquals(0, $result->type);
        $this->assertEquals(true, $result->required);
        $this->assertEquals(false, $result->visible);
    }
    

    public function testUpdateException() {
        $this->setExpectedException('InvalidArgumentException');

        $badObject = new StdClass();
        $create = $this->object->update($badObject);
    }

    public function testDeleteObject() {

        //setup
        $field = $this->createValidSectionField();

        //test delete
        $this->object->delete($field);

        //verify that it was deleted
        $this->setExpectedException('NotFoundException');
        $result = $this->object->getObjectById($field->id);
    }

    public function testDeleteId() {

        //setup
        $field = $this->createValidSectionField();
       // $this->fail("id: ".$field->id);
        $this->object->delete((int)$field->id);
        
        $this->setExpectedException('NotFoundException');
        $result = $this->object->getObjectById($field->id); 
    }
    
    public function testDeleteArray() {

        //setup
        $field = $this->createValidSectionField();
       // $this->fail("id: ".$field->id);
        $this->object->delete($field->toArray());
        
        $this->setExpectedException('NotFoundException');
        $result = $this->object->getObjectById($field->id); 
    }

    public function testDeleteException() {
        $this->setExpectedException('InvalidArgumentException');

        $badObject = new StdClass();
        $create = $this->object->delete($badObject);
    }

    public function testDeleteAll() {
//        $this->object->deleteAll();
    }

}