<?php

require_once dirname(__FILE__) . '/../../../../application/models/User/Manager.php';

/**
 * Test class for Core_Model_User_Manager.
 * Generated by PHPUnit on 2011-06-24 at 18:33:45.
 */
class Core_Model_User_ManagerTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Core_Model_User_Manager
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Core_Model_User_Manager;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }
    
    private function createValidUser(){
         $register = array(
            
             'username' => 'testUsername',
            'name' => 'testName',
            'location' => 'testLocation',
            'email' => 'test@test.com',
             'password' => 'test');
         $result = $this->object->register($register);
         
        return $result;
    }

    /**
     * @todo Implement testSetAuthClass().
     */
    public function testSetAuthClass() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testLogin().
     */
    public function testLogin() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testLogout().
     */
    public function testLogout() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    public function testRegister() {
        $result = $this->createValidUser();
        
        $this->assertInstanceOf('Core_Model_User_Interface', $result);
        
        $this->assertNotNull($result->id);
        $this->assertEquals(0, $result->status);
        $this->assertEquals(1, $result->primary_group);
        $this->assertEquals('testUsername', $result->username);
        $this->assertEquals('testName', $result->name);
        $this->assertEquals('testLocation', $result->location);
        $this->assertEquals('test@test.com', $result->email);
    }

    /**
     * @todo Implement testChangePassword().
     */
    public function testChangePassword() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testSendActivationEmail().
     */
    public function testSendActivationEmail() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }


    public function testActivate() {
        
        
        
        
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}

?>
