<h1><?php echo $this->controllerTitle ?></h1>

<?php $types = array(0 =>'System', 1 => 'Template', 2 => 'User'); ?>

<p><a class="button"  href="<?php echo $this->url(array('controller' => 'section', 'action' => 'index'), 'content'); ?>">Back to Section</a></p>

<table class="ui-widget" width="100%">
    <thead class="ui-widget-header">
        <tr><th>Label</th><th>Name</th> <th>Element</th> <th>Type</th> <th width="150">Edit/Delete</th></tr>
    </thead>
    <tbody class="ui-widget-content">
        <?php
        foreach ($this->objects as $object) {
            /* @var $object Content_Model_Category */
            ?>
            <tr  class="<?php echo $this->cycle(array("", "ui-state-highlight"))->next() ?>" >
                <td class="left"><?php echo $object->label ?></td>
                <td class="left"><?php echo $object->element ?></td>
                <td class="left"><?php echo $object->name ?></td>
                <td><?php echo $types[$object->type] ?></td>
                <td><a href="<?php echo $this->url(array('controller' => 'field', 'id' => $object->id, 'action' => 'edit'), 'content-id'); ?>">Edit</a> <a href="<?php echo $this->url(array('controller' => 'field', 'id' => $object->id, 'action' => 'delete'), 'content-id'); ?>">Delete</a></td>
            </tr><?php
        }
        ?>
    </tbody>
</table>
<a class="button"  href="<?php echo $this->url(array('controller' => 'field', 'id' => $this->id, 'action' => 'new'), 'content-id'); ?>">New</a>
