<?php echo $this->heading('Getting Started'); ?>
<section>
<p>It looks like you are in the process of setting up your HomeNet</p>
<p>You can continue where you last were</p>
</section>
<?php   
foreach ($this->houses as $house){
    $wizard = $house->getSetting('wizard');
?>
<br />
<section>
<h3 class="inline"><?php echo $house->name ?></h3>
 <a class="button cms-button-icon-right" href="<?php echo $this->url(array('controller'=>'setup', 'house' => $house->id, 'action' => 'wizard', 'wizard' => $wizard), 'homenet-house-setup') ?>">
    Continue <span class="ui-icon ui-icon-circle-arrow-e "</span>
</a>
</section>
<?php
}
?>
