<h1>Step 3</h1>
<h2>Setup the HomeNet App</h2>
<div class="transparent box">
<p>In order to link your HomeNet System to your account you have to enter an API key into the HomeNetApp. </p>

<p>Your unique api key is: </p>
</div>
<br />
<div class="transparent box">
<h2><?php echo $this->apikey ?></h2>
</div>
<br />
<div class="transparent box">
<p>If you haven't already, download and unzip HomeNet Developer Kit</p>

<p>Launch the HomeNetApp. It's in the HomeNetApp folder in the HomeNet Developer Kit</p>

<p>Copy and Paste (or type this key) into the APIKEY box in the HomeNet App</p>
</div>
<h2>Firewall Setup</h2>
<div class="transparent box">
<p>Please add a firewall exception for port 2443. This is how HomeNet connects to the Web </p>

<p>If you are behind a NAT/Firewall/Router you will also need to setup <strong>Port Forwarding</strong> on you router. You will need to forward port 2443 to your PC</p>
</div>
<h2>Test Connection</h2>
<div class="transparent box" id="test-status" style="height:50px">
<?php if(!empty($this->error)) { ?>

    <div style="padding: 0pt 0.7em;" class="ui-widget ui-state-error ui-corner-all">
                <p><span style="float: left; margin-right: 0.3em;" class="ui-icon ui-icon-alert"></span>
                    <?php echo $this->error ?></p>

</div>
                            <?php } else { ?>
<p>Press the <strong>TEST</strong> button in the HomeNet App. If it says "Successfully Connected" you are good to go</p>

<p>Next hit the  <strong>Test Connection</strong> button below to test going the other direction. If it's successful, press continue</p>
</div>
<?php } ?>
<div class="center">
<?php echo $this->ajaxLink("Test Connection", "/homenet/setup/test-connection", array('update' => '#test-status', 'class'=> 'button'));?>

<?php echo $this->form ?>
</div>
