<h1>Step 5</h1>
<h2>Upload HomeNet Code</h2>
<div class="transparent box">
<p>Connect the Node to your Computer and launch the Arduino IDE. Select the proper serial port for your node from the menu</p>
<p>Copy and Paste the code from the box below in the Arduino IDE and Upload it the node</p>
</div>
<h2>Code</h2>
<div class="transparent box">
    <pre>
    <?php echo htmlspecialchars($this->code) ?>
</pre>
</div>

<?php echo $this->form ?>

