<?php echo $this->heading('Step 3'); ?>
<h2>Setup the HomeNet App</h2>
<section>
<p>In order to link your HomeNet System to your account you have to enter an API key into the HomeNetApp. </p>

<p>Your unique api key is: </p>
</section>
<br />
<section>
<h2><?php echo $this->apikey ?></h2>
</section>
<br />
<section>
<p>If you haven't already, download and unzip HomeNet Developer Kit</p>

<p>Launch the Java HomeNetApp. Complete the setup wizard. When requested, copy and paste (or type this key) into the APIKEY field.</p>
<p>Enable the Server feature, so Homenet can push updates from the Internet.</p>
</section>
<h2>Firewall Setup</h2>
<section>
<p>If you are behind a NAT/Firewall/Router you will also need to setup <strong>Port Forwarding</strong> on you router. You will need to forward port 2443 to your PC</p>
<p>Please enable the included UPnP port forwarding or add a firewall exception for port 2443. This is how HomeNet connects to the Web </p>
</section>
<h2>Test Connection</h2>


<section id="test-status" style="height:50px">
<?php if(!empty($this->error)) { ?>

    <div style="padding: 0pt 0.7em;" class="ui-widget ui-state-error ui-corner-all">
                <p><span style="float: left; margin-right: 0.3em;" class="ui-icon ui-icon-alert"></span>
                 <?php echo $this->error ?>
                </p>
    </div>
</section>
                            <?php } else { ?>
<p>Press the <strong>TEST</strong> button in the HomeNet App. If it says "Successfully Connected" you are good to go</p>

<p>Next hit the  <strong>Test Connection</strong> button below to test going the other direction. If it's successful, press continue</p>
</div>
<?php } ?>


<div class="center">
<?php 
$url = $this->url(array('controller'=>'setup', 'action' => 'test-connection'), 'homenet');
echo $this->ajaxLink("Test Connection", $url, array('update' => '#test-status', 'class'=> 'button'));?>

<?php echo $this->form ?>
</div>
