<?php echo $this->heading('Step 6'); ?>
<h2>Test your Base Node</h2>
<section>
 <p>If you are using a Jeelink, the status LED is built in. On a Jeelink, use 2 leds to create <a href="http://code.google.com/p/homenet/wiki/DeviceStatusLights">Status Lights</a>, If you're using an Arduino, connect an LED with one leg to 3.3v, other leg to pin 9</p>
<p>Close the Arduino IDE (Only one program can connect to a serial port at a time)</p>
<p>Launch the HomeNetApp. (Restart it if it was left open to refresh the serial ports)</p>
<p>Choose the Serial Port for your device (It should be the same one you set in the Arduino IDE) </p>
    <p>Use the buttons below to turn the LED on the base station on and off</p>

    <p>Not Working? Check the <a href="http://code.google.com/p/homenet/wiki/GettingStarted">Wiki</a></p>
    
</section>
<?php /*
<ul>
    <li>A JeeNode with serial adapter</li>
    <li>A JeeLink</li>
    <li>A Arduino with an LED on Port 9</li>
</ul>
<p>Please open up the Arduino software and upload the appropriate code</p>
<p>Your First node expects to have an ID of 1</p>
<p>Connect the Node to your PC. In the HomeNet App, select the corresponding Serial Port</p>

<p>Try click these buttons to turn the Status LED on and off. If it's successful click continue</p>

    <p>This is the node connected to your PC and the HomeNetApp.  If you can try things out with an Arduino, or you can start a wireless sensor network using JeeNodes</p>
</div>

<p>Connect the Node to your PC. In the HomeNet App, select the corresponding Serial Port</p>

<p>Try click these buttons to turn the Status LED on and off. If it's successful click continue</p>

    <p>This is the node connected to your PC and the HomeNetApp.  If you can try things out with an Arduino, or you can start a wireless sensor network using JeeNodes</p>

*/ ?>
<div id="test-status" style="height:50px"  class="transparent box">
<?php if(!empty($this->error)) { ?><div class="ui-widget">
    <div style="padding: 0pt 0.7em;" class="ui-state-error ui-corner-all">
                <p><span style="float: left; margin-right: 0.3em;" class="ui-icon ui-icon-alert"></span>
                    <?php echo $this->error ?></p>
        </div>
</div><?php } ?>

</div>

<section class="center">
 <?php 
 $url = $this->url(array('controller'=>'setup', 'action' => 'test-base'), 'homenet'); // 'id' => $this->nodeId
 echo $this->ajaxLink("LED On", $url.'?command=on', array('update' => '#test-status', 'class'=> 'button'));
 echo ' ';
 echo $this->ajaxLink("LED Off", $url.'?command=off', array('update' => '#test-status', 'class'=> 'button'));?>
</section>
<br />
<div class="center">
<?php echo $this->form ?>
</div>