<?php if(!empty($this->error)) { ?><div class="ui-widget">
    <div style="padding: 0pt 0.7em;" class="ui-state-error ui-corner-all">
                <p><span style="float: left; margin-right: 0.3em;" class="ui-icon ui-icon-alert"></span>
                    <?php echo $this->error ?></p>
        </div>
</div><?php } elseif(!empty($this->success)) {?><div class="ui-widget">
        <div style="margin-top: 20px; padding: 0pt 0.7em;" class="ui-state-highlight ui-corner-all">
                <p><span style="float: left; margin-right: 0.3em;" class="ui-icon ui-icon-info"></span>
                 <?php echo $this->success ?></p>
        </div>
</div><?php } ?>