<?php echo $this->heading('Step 4'); ?>
<h2>Add your first node</h2>
<section>
<p>Your first node is going to be connected to your PC with a status LED. You will need one of the following devices:</p>
<ul>
    <li>A <a href="http://code.google.com/p/homenet/wiki/JeeNode">JeeLink</a> with serial adapter, with <a href="http://code.google.com/p/homenet/wiki/DeviceStatusLights">Status Lights</a></li>
    <li>A <a href="http://code.google.com/p/homenet/wiki/JeeLink">JeeLink</a></li>
    <li>An Arduino with a LED connect an LED (one leg to 3.3v, other leg to pin 9)</li>
</ul>
<p>Select your exact model below, and click continue</p>
</section>

<?php echo $this->form ?>