<?php echo $this->heading('Program your Base Station Node'); ?>
<h2>Upload the HomeNet Node Code</h2>
<section>
<p>Connect the Node to your computer and launch the Arduino IDE. Select the proper serial port for your node from the menu</p>
<p>Copy and Paste the code from the box below in the Arduino IDE and Upload it the node</p>
</section>
<h2>Code</h2>
<section>
    <pre><?php echo htmlspecialchars($this->code) ?></pre>
</section>

<?php echo $this->form ?>

