<?php echo $this->heading('Network Configuration'); ?>
<h2>Setup your HomeNet Network</h2>
<section>
<p>HomeNet supports a variety of network types</p>

<p>Select the <strong>Network Type</strong> of your first node. You can add additional types after the initial setup</p>
<p>Not sure the Network Type for your nodes? <a href="/contact">Let us help!</a></p>
<p>RFC: Would it be better to ask for their choice of base node and skip this step?  This allows the next pages to show just the supported network types but it may be too confusing</p>
<?php echo $this->form ?>
</div>