<?php
/*
 * Copyright (c) 2011 Matthew Doll <mdoll at homenet.me>.
 *
 * This file is part of HomeNet.
 *
 * HomeNet is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * HomeNet is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with HomeNet.  If not, see <http://www.gnu.org/licenses/>.
 */
?>
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
        <title><?php echo $this->config()->site->name ?></title>
    </head>
    <body style="margin: 0; padding: 0; background-color: #999999;" marginheight="0" topmargin="0" marginwidth="0" leftmargin="0">
        <!--100% body table-->
        <table width="100%" border="0" cellspacing="0" cellpadding="5">
            <tr>
                <td bgcolor="#666666" style="background-color: #666666; color: #FFFFFF; font-family:'lucida grande',tahoma,verdana,arial,sans-serif; font-size:24px; font-weight: bold; ">HomeNet.me</td>
            </tr>

            <tr>
                <td height="25"></td>
            </tr>

            <tr>
                <td>

                    <table width="620" border="0" align="center" cellpadding="5" cellspacing="0">

                        <tr>
                            <td bgcolor="#666666" style="background-color: #666666; color: #FFFFFF;" >
                                <?php echo $this->layout()->content ?>
                            </td>
                        </tr>

                    </table>



                </td>
            </tr>

            <tr>
                <td height="25"></td>
            </tr>

            <tr>
                <td valign="middle" align="center">
                    <table width="620" border="0" align="center" cellpadding="5" cellspacing="0">

                        <tr>
                            <td bgcolor="#FFFFFF" style="background-color: #FFFFFF; color:#000000" >
                                Sent by <?php echo $this->config()->site->name ?>, <?php echo $this->config()->resources->mail->defaultReplyTo->email ?>
                            </td>
                        </tr>

                    </table>

                </td>
            </tr>

            <tr>
                <td height="25"></td>
            </tr>



        </table>
        <!--/100% body table-->
    </body>
</html>
