<?php
/*
 * Copyright (c) 2011 Matthew Doll <mdoll at homenet.me>.
 *
 * This file is part of HomeNet.
 *
 * HomeNet is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * HomeNet is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with HomeNet.  If not, see <http://www.gnu.org/licenses/>.
 */
?>
<!doctype html>

<!--[if lt IE 7 ]> <html lang="en" class="no-js ie6"> <![endif]-->
<!--[if IE 7 ]>    <html lang="en" class="no-js ie7"> <![endif]-->
<!--[if IE 8 ]>    <html lang="en" class="no-js ie8"> <![endif]-->
<!--[if IE 9 ]>    <html lang="en" class="no-js ie9"> <![endif]-->
<!--[if (gt IE 9)|!(IE)]><!--> <html lang="en" class="no-js"> <!--<![endif]-->
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

  <?php echo $this->headTitle() ?>

  <meta name="description" content="">
  <meta name="author" content="">

  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <!--
  <link rel="shortcut icon" href="/favicon.ico">
  <link rel="apple-touch-icon" href="/apple-touch-icon.png">
-->

  <link rel="stylesheet" href="//ajax.googleapis.com/ajax/libs/jqueryui/1.8/themes/smoothness/jquery-ui.css" type="text/css" media="all" />
  <link rel="stylesheet" href="/css/style.css?v=5">
  <script src="/js/libs/modernizr-1.6.min.js"></script>

  <?php echo $this->headScript() ?>
  <?php echo $this->headStyle() ?>

</head>

<body>
<header class="transparent">
    <div id="logo"><a href="/"><?php echo $this->config()->site->name; ?></a></div>
    <div id="user">
        <?php  echo $this->action('login-widget', 'Login'); ?>
    </div>
    <nav id="top-menu">
    <ul>
        <li><a href="/about">About</a></li>
        <li><a href="http://code.google.com/p/homenet/wiki/GettingStarted">Getting Started</a></li>
        <li><a href="http://code.google.com/p/homenet/wiki/Intro">Wiki</a></li>
        <li><a href="http://code.google.com/p/homenet/downloads/list">Downloads</a></li>
        <li><a href="http://groups.google.com/group/homenetme/">Discussion</a></li>
        <li><a href="http://homenetme.blogspot.com">Blog</a></li>
        <li><a href="/contact">Contact</a></li>
    </ul>
    </nav>
    </header> 