<?php
/*
 * Copyright (c) 2011 Matthew Doll <mdoll at homenet.me>.
 *
 * This file is part of HomeNet.
 *
 * HomeNet is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * HomeNet is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with HomeNet.  If not, see <http://www.gnu.org/licenses/>.
 */
?>
<?php echo $this->render('header.phtml') ?>

<section>
    <h1><?php echo $this->layout()->heading ?></h1>
    <div class="breadcrumbs"><?php echo $this->breadcrumbs(); ?></div>
    
<?php 
echo $this->messages();
echo $this->layout()->content ?>
</section>
<?php echo $this->render('footer.phtml') ?>
  