<?php


/**
 * Test class for Content_Model_Section_Manager.
 * Generated by PHPUnit on 2011-09-10 at 03:41:22.
 */
class Content_Model_Section_ManagerTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Content_Model_Section_Manager
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Content_Model_Section_Manager;
        $installer = new Installer();
        $installer->installTest();
        $installer->loginAsSuperAdmin();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        $installer =  new Content_Installer();
        $installer->uninstallTest();
    }

    /**
     * @todo Implement testGetTemplates().
     */
    public function testGetTemplates() {
        $results = $this->object->getTemplates();
        
        foreach($results as $result){
            $this->assertTrue(is_string($result->name));
            $this->assertTrue(is_string($result->date));
            $this->assertTrue(is_string($result->version));
            $this->assertTrue(is_numeric($result->publisherId));
            $this->assertTrue(is_string($result->publisher));
            $this->assertTrue(is_string($result->publisherUrl));
            $this->assertTrue(is_string($result->supportUrl));
        }
        
       // print_r($results);
    }

    /**
     * @todo Implement testCreateBasedOnTemplate().
     */
    public function testCreateBasedOnTemplate() {
        
        $section = new Content_Model_Section();
        $section->title = 'Test Section';
        $section->url = 'test_section';
        $section->visible = false;
        
        $result = $this->object->createByTemplate($section,'Pages');
        
        $this->assertInstanceOf('Content_Model_Section_Interface', $result);
    }
    
    /**
     * @todo Implement testCreateBasedOnTemplate().
     */
    public function testDelete() {
        
//        $section = new Content_Model_Section();
//        $section->title = 'Test Section';
//        $section->url = 'test_section';
//        $section->visible = false;
//        
//        
//        $result = $this->object->createByTemplate($section,'Base');
//        
//        $this->assertInstanceOf('Content_Model_Section_Interface', $result);
    }

}