<?php


/**
 * Test class for Core_Model_User_Service.
 * Generated by PHPUnit on 2011-06-22 at 18:34:04.
 */
class Core_Model_Installer {

  public static $groupGuest;
  public static $groupMember;
  public static $groupAdmin;
  public static $groupContentAdmin;
  public static $userMember;
  public static $userSpecialMember;
  public static $userAdmin;
  public static $userSuperAdmin;

    public static function install() {
        //create groups
        $gService = new Core_Model_Group_Service();
        
        $guest = array(
            'parent' => null,
            'type' => 0,
            'title' => 'Owner',
            'description' => 'Privileges given to the creator of a content item',
            'visible' => false,
            'user_count' => 0,
            'settings' => array());

        $result = $gService->create($guest);
        self::$groupGuest = $result->id;
        $group_acls = array();
        $group_acls[] = array('group' => $result->id, 'module' => null, 'controller' => null, 'action' => 'edit',   'permission' => 1);
        $group_acls[] = array('group' => $result->id, 'module' => null, 'controller' => null, 'action' => 'delete', 'permission' => 1);
        
        $guest = array(
            'parent' => null,
            'type' => 1,
            'title' => 'Guest',
            'description' => 'Users that have not been Authenticated',
            'visible' => false,
            'user_count' => 0,
            'settings' => array());

        $result = $gService->create($guest);
        self::$groupGuest = $result->id;
        $group_acls = array();
        $group_acls[] = array('group' => $result->id, 'module' => 'core', 'controller' => 'index', 'action' => null, 'permission' => 1);
        $group_acls[] = array('group' => $result->id, 'module' => 'core', 'controller' => 'login', 'action' => null, 'permission' => 1);
        $group_acls[] = array('group' => $result->id, 'module' => 'core', 'controller' => 'index', 'action' => null, 'permission' => 1);
        $group_acls[] = array('group' => $result->id, 'module' => 'core', 'controller' => 'user', 'action' => 'next-steps', 'permission' => 1);
        
        $member = array(
            'parent' => null,
            'type' => 1,
            'title' => 'Member',
            'description' => 'Authenticated Users',
            'visible' => true);

        $result = $gService->create($member);
        self::$groupMember = $result->id;
        $group_acls[] = array('group' => $result->id, 'module' => 'core', 'controller' => 'user', 'action' => null, 'permission' => 1);
        
        $contentAdmin= array(
            'parent' => null,
            'type' => 1,
            'title' => 'Admin',
            'description' => 'Admin Site Content',
            'visible' => true);

        $result = $gService->create($contentAdmin);
        self::$groupContentAdmin = $result->id;
         $siteAdmin = array(
            'parent' => null,
            'type' => 1,
            'title' => 'Site Admin',
            'description' => 'Full access to Site',
            'visible' => false);

        $result = $gService->create($siteAdmin);
        self::$groupAdmin = $result->id;
        $group_acls[] = array('group' => $result->id, 'module' => null, 'controller' => null, 'action' => null, 'permission' => 1);

        $agService = new Core_Model_Acl_Group_Service();
        foreach($group_acl as $acl){
            $agService->create($acl);
        }
    }

    public static function uninstall(){
          $gService = new Core_Model_Group_Service();  
          $gService->deleteAll();
          
          $agService = new Core_Model_Acl_Group_Service();
          $agService->deleteAll();
          
          $ugaService = new Core_Model_Acl_User_Service();
          $agService->deleteAll();
          
          $uService = new Core_Model_User_Service();
          $uService->deleteAll();
          
          $umService = new Core_Model_User_Membership_Service();
          $umService->deleteAll();
    }
    

}