<?php echo $this->heading('Content Sections'); ?>

<div class="cms ui-widget ui-widget-content ui-corner-all">
<div class="ui-widget-content">
    <table width="100%">
        <thead class="ui-widget-header">
            <tr><th>Name</th><th>URL</th><th width="150">Templates</th><th width="150">Customize</th><th width="50"></th></tr>
        </thead>
        <tbody>
            <?php
            foreach ($this->objects as $object) {
                /* @var $object Content_Model_Category */
            ?>
            <tr  class="<?php echo $this->cycle(array("", "ui-state-default"))->next() ?>" >
                <td><a href="<?php echo $this->url(array('controller' => 'content', 'id' => $object->id), 'content-admin-id'); ?>"><?php echo $object->title ?></a></td>
                <td><?php echo $object->url ?></td>
                <td><a href="<?php echo $this->url(array('controller' => 'template', 'id' => $object->id), 'content-admin-id'); ?>">Templates</a></td>
                <td><a href="<?php echo $this->url(array('controller' => 'field', 'id' => $object->id), 'content-admin-id'); ?>">Fields</a></td>

                <td>
                    <a class="button" data-text="false" data-icon="ui-icon-pencil" title="Edit Section &quot;<?php echo $object->title ?>&quot;" 
                       href="<?php echo $this->url(array('controller' => 'section', 'id' => $object->id, 'action' => 'edit'), 'content-admin-id'); ?>">
                        Edit
                    </a> 
                    <a class="button"  data-text="false" data-icon="ui-icon-close" title="Delete Section &quot;<?php echo $object->title ?>&quot;" 
                       href="<?php echo $this->url(array('controller' => 'section', 'id' => $object->id, 'action' => 'delete'), 'content-admin-id'); ?>">
                        Delete
                    </a>
                </td>
            </tr><?php
            }
            ?>
        </tbody>
    </table>
    <a class="button" data-icon="ui-icon-plusthick" href="<?php echo $this->url(array('controller' => 'section', 'action' => 'new'), 'content-admin'); ?>">New</a>
</div>
</div>
