<div data-role="page">
    <div data-role="header">
        <h1>Login</h1>
    </div>

    <div data-role="content">
<?php

if(!empty($this->error)){
?>
<div class="ui-widget">
        <div style="padding: 0pt 0.7em;" class="ui-state-error"> 
                <p><span style="float: left; margin-right: 0.3em;" class="ui-icon ui-icon-alert"></span> 
                <strong>Error:</strong> <?php echo $this->error ?></p>
        </div>
</div>


<?php
}
?>
<?php echo $this->form ?>

   </div>

    <div data-role="footer">
        <h4>HomeNet</h4>
    </div>
</div>