<?php
/**
 * Test class for Core_Model_User_Service.
 * Generated by PHPUnit on 2011-06-22 at 18:34:04.
 */
class Core_Model_User_ServiceTest extends PHPUnit_Framework_TestCase {

   /**
     * @var Core_Model_User_Service
     */
    protected $object;
    protected $installer;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->installer = new Core_Installer();
        $this->installer->installTest();
        $this->object = new Core_Model_User_Service;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
       $this->object->deleteAll();

    }

    public function testGetMapper() {

        $this->assertInstanceOf('Core_Model_User_MapperInterface', $this->object->getMapper());
    }

    /**
     * @todo Implement testSetMapper().
     */
    public function testSetMapper() {
        
        $mapper = new Core_Model_User_MapperDbTable();
         $this->object->setMapper($mapper);
        
        $this->assertInstanceOf('Core_Model_User_MapperInterface', $this->object->getMapper());
        $this->assertEquals($mapper, $this->object->getMapper());
        //$this->ass
    }

    private function createValidUser() {
        $user = new Core_Model_User();
        
        $user->status = 0;
        $user->primary_group = $this->installer->group->members->id;
        $user->username = 'testUsername';
        $user->name = 'testName';
        $user->location = 'testLocation';
        $user->email = 'test@test.com';
        $user->permissions = null;
        $user->settings = array('test' => 'value');
        
        $result = $this->object->create($user);

        $this->assertInstanceOf('Core_Model_User_Interface', $result);
        return $result;
    }
    
    public function testCreateInvalidUser() {
        $user = new Core_Model_User();
        $user->status = 0;
        $user->primary_group = $this->installer->group->members->id;
       // $user->username = 'testUsername';
        $user->name = 'testName';
        $user->location = 'testLocation';
        $user->email = 'test@test.com';
        $user->permissions = "";
        $user->settings = array('test' => 'value');
        $this->setExpectedException('Exception');
        $result = $this->object->create($user);
    }
//    
//    public function testDuplicateUrl() {
//
//        $user1 = $this->createValidUser();
//        $this->setExpectedException('DuplicateEntryException');
//        $user2 = $this->createValidUser();
//    }

    public function testCreateValidFromObject() {

        $result = $this->createValidUser();

        $this->assertNotNull($result->id);
        $this->assertEquals(0, $result->status);
        $this->assertEquals($this->installer->group->members->id, $result->primary_group);
        $this->assertEquals('testUsername', $result->username);
        $this->assertEquals('testName', $result->name);
        $this->assertEquals('testLocation', $result->location);
        $this->assertEquals('test@test.com', $result->email);
        $this->assertEquals(null, $result->permissions);
        $this->assertArrayHasKey('test', $result->settings);
    }
    
     public function testToArray() {

        $user = new Core_Model_User();
        
        $user->status = 0;
        $user->primary_group = 1;
        $user->username = 'testUsername';
        $user->name = 'testName';
        $user->location = 'testLocation';
        $user->email = 'test@test.com';
        $user->permissions = null;
        $user->settings = array('test' => 'value');

        $array = $user->toArray();
        
        $this->assertArrayHasKey('primary_group', $array);
        $this->assertEquals(1, $array['primary_group']);
    }
    
    public function testCreateFromArray() {

        $user = array(
            'status' => 0,
            'primary_group' => $this->installer->group->members->id,
            'username' => 'testUsername',
            'name' => 'testName',
            'location' => 'testLocation',
            'email' => 'test@test.com',
            'permissions' => null,
            'settings' => array('test' => 'value'));

        $result = $this->object->create($user);

        $this->assertInstanceOf('Core_Model_User_Interface', $result);

        $this->assertNotNull($result->id);
        $this->assertEquals(0, $result->status);
        $this->assertEquals($this->installer->group->members->id, $result->primary_group);
        $this->assertEquals('testUsername', $result->username);
        $this->assertEquals('testName', $result->name);
        $this->assertEquals('testLocation', $result->location);
        $this->assertEquals('test@test.com', $result->email);
        $this->assertEquals(null, $result->permissions);
        $this->assertArrayHasKey('test', $result->settings);
    }

    public function testCreateException() {
        $this->setExpectedException('InvalidArgumentException');

        $badObject = new StdClass();
        $create = $this->object->create($badObject);
    }

    public function testGetObjectById() {

        //setup
        $user = $this->createValidUser();

        //test getObject
        $result = $this->object->getObjectById($user->id);
        
        $this->assertInstanceOf('Core_Model_User_Interface', $result);

        $this->assertNotNull($result->id);
        $this->assertEquals(0, $result->status);
        $this->assertEquals($this->installer->group->members->id, $result->primary_group);
        $this->assertEquals('testUsername', $result->username);
        $this->assertEquals('testName', $result->name);
        $this->assertEquals('testLocation', $result->location);
        $this->assertEquals('test@test.com', $result->email);
        $this->assertEquals(null, $result->permissions);
        $this->assertArrayHasKey('test', $result->settings);
    }
    
//    public function testGetObjectByUrl() {
//
//        //setup
//        $user = $this->createValidUser();
//
//        //test getObject
//        $result = $this->object->getObjectByUrl($user->url);
//        
//        $this->assertInstanceOf('Core_Model_User_Interface', $result);
//
//        $this->assertEquals($user->id, $result->id);
//        $this->assertEquals(0, $result->set);
//        $this->assertEquals(1, $result->parent);
//        $this->assertEquals(2, $result->order);
//        $this->assertEquals('testUrl', $result->url);
//        $this->assertEquals('testTitle', $result->title);
//        $this->assertEquals('testDescription', $result->description);
//    }
//    
//     public function testGetInvalidObjectByUrl() {
//
//        $this->setExpectedException('NotFoundException');
//        $result = $this->object->getObjectByUrl("testnotindatabase");
//
//    }

    public function testUpdateFromObject() {

        //setup
        $user = $this->createValidUser();

        //update values
        $user->status = 1;
        $user->primary_group = $this->installer->group->admins->id;
        $user->username = 'testUsername2';
        $user->name = 'testName2';
        $user->location = 'testLocation2';
        $user->email = 'test2@test.com';
        $user->permissions = array();
        $user->settings = array('test2' => 'value');

        $result = $this->object->update($user);

        $this->assertInstanceOf('Core_Model_User_Interface', $result);

        $this->assertEquals($user->id,$result->id);
        $this->assertEquals(1, $result->status);
        $this->assertEquals($this->installer->group->admins->id, $result->primary_group);
        $this->assertEquals('testUsername2', $result->username);
        $this->assertEquals('testName2', $result->name);
        $this->assertEquals('testLocation2', $result->location);
        $this->assertEquals('test2@test.com', $result->email);
        $this->assertEquals(array(), $result->permissions);
        $this->assertArrayHasKey('test2', $result->settings);
        $this->assertEquals('value', $result->getSetting('test2'));
    }
    
    public function testUpdateFromArray() {

        //setup
        $user = $this->createValidUser();

        $array = $user->toArray();
        
        //update values      
        $array['status'] = 1;
        $array['primary_group'] = $this->installer->group->admins->id;
        $array['username'] = 'testUsername2';
        $array['name'] = 'testName2';
        $array['location'] = 'testLocation2';
        $array['email'] = 'test2@test.com';
        $array['permissions'] = array();
        $array['settings'] = array('test2' => 'value');


        $result = $this->object->update($array);

        $this->assertInstanceOf('Core_Model_User_Interface', $result);

        $this->assertEquals($user->id,$result->id);
        $this->assertEquals(1, $result->status);
        $this->assertEquals($this->installer->group->admins->id, $result->primary_group);
        $this->assertEquals('testUsername2', $result->username);
        $this->assertEquals('testName2', $result->name);
        $this->assertEquals('testLocation2', $result->location);
        $this->assertEquals('test2@test.com', $result->email);
        $this->assertEquals(array(), $result->permissions);
        $this->assertArrayHasKey('test2', $result->settings);
        $this->assertEquals('value', $result->getSetting('test2'));
    }
    

    public function testUpdateException() {
        $this->setExpectedException('InvalidArgumentException');

        $badObject = new StdClass();
        $create = $this->object->update($badObject);
    }

    public function testDeleteObject() {

        //setup
        $user = $this->createValidUser();

        //test delete
        $this->object->delete($user);

        //verify that it was deleted
        $this->setExpectedException('NotFoundException');
        $result = $this->object->getObjectById($user->id);
    }

    public function testDeleteId() {

        //setup
        $user = $this->createValidUser();
       // $this->fail("id: ".$user->id);
        $this->object->delete((int)$user->id);
        
        $this->setExpectedException('NotFoundException');
        $result = $this->object->getObjectById($user->id); 
    }
    
    public function testDeleteArray() {

        //setup
        $user = $this->createValidUser();
       // $this->fail("id: ".$user->id);
        $this->object->delete($user->toArray());
        
        $this->setExpectedException('NotFoundException');
        $result = $this->object->getObjectById($user->id); 
    }

    public function testDeleteException() {
        $this->setExpectedException('InvalidArgumentException');

        $badObject = new StdClass();
        $create = $this->object->delete($badObject);
    }

    public function testDeleteAll() {
//        $this->object->deleteAll();
    }

}