<?php

/**
 * Test class for HomeNet_Model_Node_Service.
 * Generated by PHPUnit on 2011-11-21 at 16:35:57.
 */
class HomeNet_Model_Node_ServiceTest extends PHPUnit_Framework_TestCase {

    /**
     * @var HomeNet_Model_Node_Service
     */
    protected $service;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->service = new HomeNet_Model_Node_Service;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        $this->service->deleteAll();
        $service = new HomeNet_Model_NodeModel_Service;
        $service->deleteAll();
    }
    
     private function _fillObject($object, $seed = 0) {
        $data = $this->_getTestData($seed);
        foreach ($data as $key => $value) {
            $object->$key = $value;
        }
        return $object;
    }
    private function _fillArray($array, $seed = 0) {
        if(is_object($array)){
            $array = $array->toArray();
        }
        
        return array_merge($array, $this->_getTestData($seed));
    }
    
    private function _getTestData($seed = 0) {
        
          //create node model
        $array = array('type' => HomeNet_Model_Node::SENSOR,
            'status' => HomeNet_Model_ComponentModel::LIVE,
            'plugin' => 'Jeenode',
            'name' => 'testModel',
            'description' => 'test description',
            'image' => 'test.jpg',
            'max_devices' => 4,
            'settings' => array('key' => 'value'));
        $service = new HomeNet_Model_NodeModel_Service;
        $model = $service->create($array);

        return $array = array(
            'status' => HomeNet_Model_Node::STATUS_LIVE,
            'address' => 1 + $seed,
            'model' => $model->id,
            'uplink' => 1 + $seed,
            'house' => 4 + $seed,
            'room' => 5 + $seed,
            'description' => 'test description' . $seed,
            'settings' => array('key' => 'value' . $seed));
    }
    
    private function _createValidObject($seed = 0) {
        $object = new HomeNet_Model_Node();
        $object = $this->_fillObject($object, $seed);
  
        $result = $this->service->create($object);

        $this->assertInstanceOf('HomeNet_Model_Node_Interface', $result);
        return $result;
    }
    
    private function _validateResult($result, $seed = 0){
        
        $this->assertInstanceOf('HomeNet_Model_Node_Interface', $result);
        $this->assertNotNull($result->id);
        $this->assertEquals(1+$seed, $result->address);
      //  $this->assertEquals(2, $result->model);
        $this->assertEquals(1+$seed, $result->uplink);
        $this->assertEquals(4+$seed, $result->house);
        $this->assertEquals(5+$seed, $result->room);
        $this->assertEquals('test description'.$seed, $result->description);
        $this->assertTrue(is_array($result->settings));
        $this->assertEquals('value'.$seed, $result->settings['key']);
    }

    

//$this->service->getMapper()///////////////////////////////////////////////////    
    public function testGetMapper() {
       $this->assertInstanceOf('HomeNet_Model_Node_MapperInterface', $this->service->getMapper());
    }

//$this->service->setMapper($mapper)////////////////////////////////////////////
    public function testSetMapper() {
        $mapper = new HomeNet_Model_Node_MapperDbTable();
         $this->service->setMapper($mapper);
        
        $this->assertInstanceOf('HomeNet_Model_Node_MapperInterface', $this->service->getMapper());
        $this->assertEquals($mapper, $this->service->getMapper());
    }
    
//$this->service->getObjectById($id)////////////////////////////////////////////
   public function testGetObjectById_valid() {
        $object = $this->_createValidObject();
        
        $result = $this->service->getObjectById($object->id);
        
        $this->_validateResult($result);
    }

    public function testGetObjectById_invalid() {
        $this->setExpectedException('NotFoundException');
        $this->service->getObjectById(1000);
    }

    public function testGetObjectById_null() {
        $this->setExpectedException('InvalidArgumentException');
        $this->service->getObjectById(null);
    }

//$this->service->getObjectByHouse($house)//////////////////////////////////////
    public function testGetObjectsByHouse_valid() {
        $object = $this->_createValidObject();
        
        $results = $this->service->getObjectsByHouse($object->house);

        $this->assertEquals(1, count($results));
        $this->_validateResult($results[0]);
    }
     public function testGetObjectsByHouse_null() {
        $this->setExpectedException('InvalidArgumentException');
        $results = $this->service->getObjectsByHouse(null);
    }
    
//$this->service->getTrashedObjectsByHouse($house)//////////////////////////////
    public function testGetTrashedObjectsByHouse_valid() {
        $object = $this->_createValidObject();
        $results = $this->service->getTrashedObjectsByHouse($object->house);
        $this->assertEquals(0, count($results));
       // $this->_validateResult($results[0]);
    }
    public function testGetTrashedObjectsByHouse_null() {
        $this->setExpectedException('InvalidArgumentException');
        $results = $this->service->getTrashedObjectsByHouse(null);
    }
    
//$this->service->getObjectByRoom($room)////////////////////////////////////////
    public function testGetObjectsByRoom_valid() {
        $object = $this->_createValidObject();
        $results = $this->service->getObjectsByRoom($object->room);
        $this->assertEquals(1, count($results));
        $this->_validateResult($results[0]);
    }
    public function testGetObjectsByRoom_null() {
        $this->setExpectedException('InvalidArgumentException');
        $results = $this->service->getObjectsByRoom(null);
    }
    
//$this->service->getObjectByHouseAddress($house, $address)/////////////////////
    public function testGetObjectByHouseAddress_valid() {
        $object = $this->_createValidObject();
        $result = $this->service->getObjectByHouseAddress($object->house, $object->address);
        
        $this->_validateResult($result);
    }
    public function testGetObjectByHouseAddress_houseNull() {
        $this->setExpectedException('InvalidArgumentException');
        $result = $this->service->getObjectByHouseAddress(null, 1);
    }
    public function testGetObjectByHouseAddress_addressNull() {
        $this->setExpectedException('InvalidArgumentException');
        $result = $this->service->getObjectByHouseAddress(1, null);
    }
    public function testGetObjectByHouseAddress_notFound() {
        $this->setExpectedException('NotFoundException');
        $result = $this->service->getObjectByHouseAddress(100, 100);
    }

//$this->service->getNextAddressByHouse($house)/////////////////////////////////
    public function testGetNextAddressByHouse_valid() {
        $object = $this->_createValidObject();
        $result = $this->service->getNextAddressByHouse($object->house);

        $this->assertGreaterThan($object->address, $result);
    }
    public function testGetNextAddressByHouse_null() {
        $this->setExpectedException('InvalidArgumentException');
        $result = $this->service->getNextAddressByHouse(null);
    }
    public function testGetNextAddressByHouse_notFound() {
        $this->setExpectedException('NotFoundException');
        $result = $this->service->getNextAddressByHouse(100);
    }

//$this->service->getObjectsByHouseType($house, $type)//////////////////////////
    public function testGetObjectsByHouseType_valid() {
        $object = $this->_createValidObject();
        
        $results = $this->service->getObjectsByHouseType($object->house, HomeNet_Model_Node::SENSOR);
        $this->assertEquals(1, count($results));
        $this->_validateResult($results[0]);
    }
    public function testGetObjectsByHouseType_houseNull() {
        $this->setExpectedException('InvalidArgumentException');
        $results = $this->service->getObjectsByHouseType(null, HomeNet_Model_Node::SENSOR);
    }
     public function testGetObjectsByHouseType_statusNull() {
        $this->setExpectedException('InvalidArgumentException');
        $results = $this->service->getObjectsByHouseType(100, null);
    }
//$this->service->getUplinksByHouse($house)/////////////////////////////////////
    /**
     * @todo create internet node to test against
     */
    public function testGetUplinksByHouse_valid() {
        $object = $this->_createValidObject();
        
        $results = $this->service->getUplinksByHouse($object->house);
        $this->assertEquals(0, count($results));
    }
    public function testGetUplinksByHouse_null() {
        $this->setExpectedException('InvalidArgumentException');
        
        $results = $this->service->getUplinksByHouse(null);
    }
    
//$this->service->newObjectFromModel($model)////////////////////////////////////
    public function testNewObjectByModel_valid() {
        $object = $this->_createValidObject();
        $result = $this->service->newObjectFromModel($object->model);
        
        $this->assertInstanceOf('HomeNet_Model_Node_Abstract', $result);
    }
//    public function testNewObjectByModel_missingPlugin() {
//        $object = $this->_createValidObject();
//        $object->plugin = null;
//        $this->setExpectedException('InvalidArgumentException');
//        $result = $this->service->newObjectFromModel($object->model);
//
//    }
//    public function testNewObjectByModel_badPlugin() {
//        $this->setExpectedException('InvalidArgumentException');
//        $result = $this->service->newObjectFromModel(null);
//    }
    
//$this->service->setStatusToDeleted($object)///////////////////////////////////
    public function testTrash(){
        $object = $this->_createValidObject();
        $result = $this->service->trash($object);
        $this->assertEquals(HomeNet_Model_Node::STATUS_TRASHED, $result->status);
    }
    
//$this->service->setStatusToLive($object)//////////////////////////////////////
    public function testUntrash(){
        $object = $this->_createValidObject();
        $object->status = HomeNet_Model_Node::STATUS_TRASHED;
        $result = $this->service->untrash($object);
        $this->assertEquals(HomeNet_Model_Node::STATUS_LIVE, $result->status);
        
    }
    
//$this->service->create($mixed)////////////////////////////////////////////////
    public function testCreate_validObject() {
        $result = $this->_createValidObject();

        $this->_validateResult($result);
    }

    public function testCreate_validArray() {
        $array = $this->_getTestData();
        
        $result = $this->service->create($array);

        $this->_validateResult($result);
    }

    public function testCreate_invalidObject() {
        $this->setExpectedException('InvalidArgumentException');

        $badObject = new StdClass();
        $this->service->create($badObject);
    }
    
//$this->service->update($mixed)////////////////////////////////////////////////
    public function testUpdate_validObject() {
        //setup
        $object = $this->_createValidObject();

        //update values
        $object = $this->_fillObject($object, 1);

        $result = $this->service->update($object);

        $this->_validateResult($result, 1);
    }

    public function testUpdate_validArray() {
        //setup
        $object = $this->_createValidObject();
        $array = $object->toArray();

        //update values
        $array = $this->_fillArray($array, 1);

        $result = $this->service->update($array);

        $this->_validateResult($result, 1);
    }

    public function testUpdate_invalidObject() {
        $this->setExpectedException('InvalidArgumentException');

        $badObject = new StdClass();
        $create = $this->service->update($badObject);
    }

//$this->service->delete($mixed)////////////////////////////////////////////////    
    public function testDelete_validObject() {
        //setup
        $object = $this->_createValidObject();

        //test delete
        $this->service->delete($object);

        //verify that it was deleted
        $this->setExpectedException('NotFoundException');
        $result = $this->service->getObjectById($object->id);
    }

    public function testDelete_validArray() {
        //setup
        $object = $this->_createValidObject();

        //test delete
        $this->service->delete($object->toArray());

        //verify that it was deleted
        $this->setExpectedException('NotFoundException');
        $result = $this->service->getObjectById($object->id);
    }

    public function testDelete_validId() {
        //setup
        $object = $this->_createValidObject();

        //test delete
        $this->service->delete($object->id);

        //verify that it was deleted
        $this->setExpectedException('NotFoundException');
        $result = $this->service->getObjectById($object->id);
    }

    public function testDelete_invalidObject() {
        $this->setExpectedException('InvalidArgumentException');

        $badObject = new StdClass();
        $create = $this->service->delete($badObject);
    }
}