<h1><?php echo $this->controllerTitle ?></h1>

<p><a class="button"  href="<?php echo $this->url(array('controller' => 'category-set', 'action' => 'index'), 'content'); ?>">Back to Sets</a></p>

<table class="ui-widget" width="100%">
    <thead class="ui-widget-header">
        <tr><th width="50">ID</th><th>Name</th> <th>Url</th> <th width="150">Edit/Delete</th></tr>
    </thead>
    <tbody class="ui-widget-content">
        <?php
        foreach ($this->objects as $object) {
            /* @var $object Content_Model_Category */
            ?>
            <tr  class="<?php echo $this->cycle(array("", "ui-state-highlight"))->next() ?>" >
                <td><?php echo $object->id ?></td>
                <td class="left"><?php echo $object->title ?></td>
                <td class="left"><?php echo $object->url ?></td>
                <td><a href="<?php echo $this->url(array('controller' => 'category', 'id' => $object->id, 'action' => 'edit'), 'content-id'); ?>">Edit</a> <a href="<?php echo $this->url(array('controller' => 'category', 'id' => $object->id, 'action' => 'delete'), 'content-id'); ?>">Delete</a></td>
            </tr><?php
        }
        ?>
    </tbody>
</table>
<a class="button"  href="<?php echo $this->url(array('controller' => 'category', 'id' => $this->id, 'action' => 'new'), 'content-id'); ?>">New</a>
