<?php echo $this->heading($this->heading); ?>

<div class="ui-widget-content buttonfix">
    <a class="button" data-icon="ui-icon-circle-arrow-w" href="<?php echo $this->url(array('controller' => 'category-set', 'action' => 'index'), 'content-admin'); ?>">Back to Sets</a>
</div>    
<div class="cms ui-widget ui-widget-content ui-corner-all">
<div class="ui-widget-content">
    <table width="100%">
        <thead class="ui-widget-header">
            <tr><th width="50">ID</th><th>Name</th> <th>Url</th> <th width="50"></th></tr>
        </thead>
        <tbody>
            <?php
            foreach ($this->objects as $object) {
                /* @var $object Content_Model_Category */
            ?>
            <tr  class="<?php echo $this->cycle(array("", "ui-state-default"))->next() ?>" >
                <td><?php echo $object->id ?></td>
                <td class="left"><?php echo $object->title ?></td>
                <td class="left"><?php echo $object->url ?></td>
                <td>
                    <a class="button" data-text="false" data-icon="ui-icon-pencil" title="Edit Category &quot;<?php echo $object->title ?>&quot;" 
                       href="<?php echo $this->url(array('controller' => 'category', 'id' => $object->id, 'action' => 'edit'), 'content-admin-id'); ?>">
                        <span class="ui-icon ui-icon-pencil"></span>
                    </a> 
                    <a class="button" data-text="false" data-icon="ui-icon-close" title="Delete Category &quot;<?php echo $object->title ?>&quot;" 
                       href="<?php echo $this->url(array('controller' => 'category', 'id' => $object->id, 'action' => 'delete'), 'content-admin-id'); ?>">
                        <span class="ui-icon ui-icon-closethick"></span>
                    </a>
                </td>
            </tr>
            <?php
            }
            ?>
        </tbody>
    </table>
    <a class="button" data-icon="ui-icon-plusthick" href="<?php echo $this->url(array('controller' => 'category', 'id' => $this->id, 'action' => 'new'), 'content-admin-id'); ?>">New</a>
</div>
