<?php

require_once dirname(__FILE__) . '/../../../../application/models/Reflection/Service.php';

/**
 * Test class for Core_Model_Reflection_Service.
 * Generated by PHPUnit on 2011-09-19 at 01:14:28.
 */
class Core_Model_Reflection_ServiceTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Core_Model_Reflection_Service
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Core_Model_Reflection_Service;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @todo Implement testGetModules().
     */
    public function testGetModules() {
       $results = $this->object->getModules();
       $this->assertArrayHasKey('Core', $results);
    }

    public function testGetValidModulePath() {
       $result = $this->object->getModulePath('Core');
      // $this->assertStringStartsWith('application', $result);
       $this->assertTrue(strstr($result,'application'));
    }
    
    public function testGetInvalidModulePath() {
       $this->setExpectedException('Exception');
       $this->object->getModulePath('DoesNotExists');
    }
    
    public function testGetPluginTypesByModule() {
         $results = $this->object->getPluginTypesByModule('Content');
         $this->assertEquals(2,count($results));

    }

    /**
     * @todo Implement testGetControllersByModule().
     */
    public function testGetControllersByModule() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testGetPluginTypes().
     */
    public function testGetPluginTypes() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }
    
    public function testGetPluginConfigsByModuleType() {
        $results = $this->object->getPluginConfigsByModuleType('Content','Element');
        foreach($results as $key => $value){
            $this->assertInstanceOf('Zend_Config_Ini', $value);
        }
        die(debugArray($results));
         $this->assertEquals(2,count($results));
    }

    /**
     * @todo Implement testGetActionsByModuleController().
     */
    public function testGetActionsByModuleController() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testGetTemplates().
     */
    public function testGetTemplates() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testGetTemplateInstaller().
     */
    public function testGetTemplateInstaller() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}

?>
