<?php
/*
echo '<ul id="nav1">';
// loop root level (only has Home, but later may have an Admin root page?)
foreach ($this->container as $page) {
    // check if it is active (not recursive)
    $isActive = $page->isActive(false);
    $liClass = $isActive ? ' class="active"' : '';
    echo '<li ' . $liClass . '>' . $this->menu()->htmlify($page) . '</li>', PHP_EOL;
    // loop next level
    foreach ($page as $page) {
        // check if it is active (recursive)
        $isActive = $page->isActive(true);
        $liClass = $isActive ? ' class="active"' : '';
        echo '<li ' . $liClass . '>' . $this->menu()->htmlify($page) . '</li>', PHP_EOL;
    }
}
echo '</ul>'; */
?>
<?php
$html = array ();
//data-theme="g"
$html[] = '<ul class="navMenu ui-widget ui-state-default ui-corner-all">';
foreach ( $this->container as $page1 ) {
    //$depth = $iterator->getDepth ();
    $html [] = '<li><div class="ui-widget-header ui-corner-top"><a href="' . $page1->getHref() . '">' . $page1->getLabel().'</a></div>';
    $html [] = '<ul>';
    
    foreach ( $page1 as $page2 ) {
        
        $html [] = '<li><div class="house-region">' . $page2->getLabel().'</div>' ;
        $html [] = '<ul>';
        foreach ( $page2 as $page3 ) {
            
            $html [] = '<li><a href="' . $page3->getHref() . '/">' . $page3->getLabel() . '</a></li>';
            
        }

  //      'label' => 'New',
//            'class' => 'room-new',
//            'route' => 'homenet-room-add',
//            'params' => array('house' => $this->_house, 'region' => $this->_region)

     //   $html [] = '<li class="room-new"><a href="' . $this->url($page1->getParams(),'homenet') . '/">New</a></li>';
        $html [] = '</ul></li>';
    }
    $html [] = '</ul></li>';
}

$html [] = '</ul>';
echo implode( '', $html);