<?php
/*
echo '<ul id="nav1">';
// loop root level (only has Home, but later may have an Admin root page?)
foreach ($this->container as $page) {
    // check if it is active (not recursive)
    $isActive = $page->isActive(false);
    $liClass = $isActive ? ' class="active"' : '';
    echo '<li ' . $liClass . '>' . $this->menu()->htmlify($page) . '</li>', PHP_EOL;
    // loop next level
    foreach ($page as $page) {
        // check if it is active (recursive)
        $isActive = $page->isActive(true);
        $liClass = $isActive ? ' class="active"' : '';
        echo '<li ' . $liClass . '>' . $this->menu()->htmlify($page) . '</li>', PHP_EOL;
    }
}
echo '</ul>'; */
?>
<?php
$html = array ();
//data-theme="g"
$html[] = '<ul data-role="listview"  data-inset="true">';
$html [] = '<li data-role="list-divider">Homes</li>';

foreach ( $this->container as $page1 ) {
    //$depth = $iterator->getDepth ();
    $html [] = '<li>' . $page1->getLabel();
    $html [] = '<ul>';
    
    foreach ( $page1 as $page2 ) {
        
        $html [] = '<li data-role="list-divider">' . $page2->getLabel() . '</li>';
        
        foreach ( $page2 as $page3 ) {
            
            $html [] = '<li><a data-ajax="false" href="' . $page3->getHref() . '/">' . $page3->getLabel() . '</a></li>';
            
        }
    }
    $html [] = '</ul></li>';
}

$html [] = '</ul>';
echo implode( '', $html);
?>