<h1>Category Sets</h1>
<table>
<?php
foreach($objects as $object){
    /*@var $object Core_Model_Category */
 ?>
    <tr>
     <td><a href="/category-set/<?php echo $object->id ?>"><?php echo $object->title ?></a></td>
     <td><a href="/category-set/edit/<?php echo $object->id ?>">Edit</a></td>
     <td><a href="/category-set/delete/<?php echo $object->id ?>">Delete</a></td>
    </tr><?php

}
?>
 </table>
<a href="/category-set/new">New</a>

<?php /*
 * <h1>Node List</h1>

<table class="ui-widget" width="100%">
  <thead class="ui-widget-header">
    <tr><th width="30">ID</th><th>Name</th><th>Description</th><th width="150">Edit/Delete</th></tr>
    </thead>
    <tbody class="ui-widget-content">
<?php foreach($this->nodes as $node){ ?>
<tr class="<?php echo $this->cycle(array("","ui-state-highlight"))->next()?>">
    <td><?php echo $node->node ?></td>
    <td><?php echo $node->modelName ?></td>
    <td><?php echo $node->description ?></td>
    <td><a class="button" href="<?php echo $this->url(array('house'=>$this->house, 'node'=>$node->id, 'action'=>'index'),'homenet-node'); ?>"><span class="ui-icon ui-icon-wrench"></span></a>
        <a class="button" href="<?php echo $this->url(array('house'=>$this->house, 'node'=>$node->id, 'action'=>'edit'),'homenet-node'); ?>"><span class="ui-icon ui-icon-pencil"></span></a>
        <a class="button" href="<?php echo $this->url(array('house'=>$this->house, 'node'=>$node->id, 'action'=>'remove'),'homenet-node'); ?>"><span class="ui-icon ui-icon-closethick"></span></a></td>
</tr>
<?php } ?>
</tbody>
</table>
<a class="button" href="<?php echo $this->url(array('house'=>$this->house),'homenet-node-add'); ?>">Add Node</a>
<a class="button" href="<?php echo $this->url(array('house'=>$this->house),'homenet-apikeys'); ?>">API Keys</a>
 * 
 */
